
// src/providers/language-provider.tsx
'use client';

import type { ReactNode } from 'react';
import { createContext, useState, useEffect, useCallback } from 'react';
import { LANGUAGES } from '@/lib/constants';

export type LanguageCode = typeof LANGUAGES[number]['code'];

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  translations: Record<string, string>;
  hydrated: boolean; 
}

const translationsData: Record<LanguageCode, Record<string, string>> = {
  en: {
    'app.name': 'SimulTradex',
    'app.loadingMessage': 'Loading SimulTradex...',
    'settings.title': 'Settings',
    'settings.myAccount': 'My Account',
    'settings.accountSettings': 'Account Settings',
    'settings.language': 'Language',
    'settings.logout': 'Log out',
    'header.userMenu.title': 'User Menu',
    'dashboard.title': 'Dashboard',
    'dashboard.marketOverview': 'Market Overview',
    'dashboard.orderSimulator': 'Order Simulator',
    'dashboard.opportunitySimulator': 'Opportunity Simulator',
    'dashboard.loadingPrices': 'Loading live prices...',
    'dashboard.portfolioBalance': 'Portfolio Balance',
    'dashboard.portfolioBalance.publicSourceMessage': "Displaying market data from public source.",
    'dashboard.connectionStatus.title': 'Connection Issue',
    'dashboard.connectionStatus.noFeed': 'Currently not receiving live price updates. Attempting to connect...',
    'dashboard.connectionStatus.fallbackTitle': 'Using Fallback Connection',
    'dashboard.connectionStatus.restFallbackActive': 'WebSocket connection failed. Using periodic REST API updates for prices.',
    'dashboard.cryptoCard.alertButton.title': 'Set Price Alert',
    'dashboard.cryptoCard.alertButton.label': 'Set Alert',
    'dashboard.alerts.fetchErrorTitle': 'Alerts Error',
    'dashboard.alerts.fetchErrorDescription': 'Could not load your active price alerts.',
    'dashboard.alerts.triggeredTitle': 'Price Alert Triggered!',
    'dashboard.alerts.triggeredDescription': '{symbol} has reached your target price of ${targetPrice}. Current price: ${currentPrice}.',
    'dashboard.ai.historicalDataError': 'Could not fetch historical data for {symbol}.',


    'login.title': 'Log In',
    'login.description': 'Log in to your account',
    'login.emailLabel': 'Email',
    'login.emailPlaceholder': 'you@example.com',
    'login.passwordLabel': 'Password',
    'login.submitButton': 'Log In',
    'login.signupPrompt': "Don't have an account?",
    'login.signupLink': 'Sign up',
    'login.error.invalidCredentials': 'Invalid email or password.',
    'login.error.unknown': 'An unknown error occurred.',
    'login.error.passwordTooWeak': 'Password does not meet security requirements. Must be 8+ chars, include uppercase, lowercase, number, and symbol.',
    'login.required': 'Please log in to view this information.',
    'signup.title': 'Sign Up',
    'signup.description': 'Create your account',
    'signup.emailLabel': 'Email',
    'signup.emailPlaceholder': 'you@example.com',
    'signup.passwordLabel': 'Password',
    'signup.confirmPasswordLabel': 'Confirm Password',
    'signup.submitButton': 'Sign Up',
    'signup.loginPrompt': 'Already have an account?',
    'signup.loginLink': 'Log in',
    'signup.error.unknown': 'An unknown error occurred.',
    'signup.error.emailTaken': 'This email is already registered.',
    'signup.error.passwordTooWeak': 'Password does not meet security requirements. Must be 8+ chars, include uppercase, lowercase, number, and symbol.',
    
    'account.passwordChange.title': "Change Password",
    'account.passwordChange.description': "Update your account password.",
    'account.passwordChange.currentPasswordLabel': "Current Password",
    'account.passwordChange.newPasswordLabel': "New Password",
    'account.passwordChange.confirmNewPasswordLabel': "Confirm New Password",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "Change Password",
    'account.passwordChange.toast.changedTitle': "Password Changed",
    'account.passwordChange.toast.changedDescription': "Your password has been successfully updated.",
    'account.passwordChange.toast.failedTitle': "Password Change Failed",
    'account.passwordChange.toast.failedDescriptionIncorrect': "Incorrect current password.",
    'account.passwordChange.toast.failedDescriptionWeak': 'New password does not meet security requirements.',

    'account.page.title': "Account Settings",
    'account.page.userInfoTitle': "User Information",
    'account.page.emailLabel': "Email:",

    'dashboard.cryptoCard.tooltip.reason': "Reason:",
    'dashboard.cryptoCard.tooltip.confidence': "Confidence:",
    'dashboard.cryptoCard.trend.upward': "Upward trend",
    'dashboard.cryptoCard.trend.downward': "Downward trend",
    'dashboard.cryptoCard.trend.sideways': "Sideways trend",
    'dashboard.cryptoCard.trend.notAvailable': "Trend N/A",

    'dashboard.orderOpportunitySimulator.title': 'Order & Opportunity Simulator',
    'dashboard.orderOpportunitySimulator.description': 'Simulate an exchange and see potential sell opportunities at incremental profit percentages.',
    'dashboard.orderOpportunitySimulator.operationPairLabel': 'Trading Pair',
    'dashboard.orderOpportunitySimulator.inputAmountLabel': 'Amount ({currency})',
    'dashboard.orderOpportunitySimulator.purchasePriceUsdtLabel': 'Purchase Price of {targetCrypto} (USDT)',
    'dashboard.orderOpportunitySimulator.marketPairPriceLabel': 'Market Price ({pair})',
    'dashboard.orderOpportunitySimulator.inputDivPurchasePriceLabel': 'Input Amt / Purch. Price',
    'dashboard.orderOpportunitySimulator.marketPriceDisplayLabel': 'Market Price ({cur2}/{cur1})',
    'dashboard.orderOpportunitySimulator.selectPairPlaceholder': 'Select Trading Pair',
    'dashboard.orderOpportunitySimulator.table.header.operation': 'Operation',
    'dashboard.orderOpportunitySimulator.table.header.amountCur1Display': 'Amount ({currency1})',
    'dashboard.orderOpportunitySimulator.table.header.marketPriceDisplay': 'Market Price',
    'dashboard.orderOpportunitySimulator.table.header.amountCur2Display': 'Amount ({currency2})',
    'dashboard.orderOpportunitySimulator.table.header.commissionDisplay': 'Commission ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.netProfitDisplay': 'Net Profit ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.actions': 'Actions',
    'dashboard.orderOpportunitySimulator.exchangeOperation': 'Exchange {cur1} for {cur2}',
    'dashboard.orderOpportunitySimulator.sellOperationPerc': 'Sell {targetCrypto} (+{perc}%)',
    'dashboard.orderOpportunitySimulator.priceUnavailable': 'Price N/A',
    'dashboard.orderOpportunitySimulator.priceUnavailableShort': 'N/A',
    'dashboard.orderOpportunitySimulator.invalidMarketPrice': 'Invalid Market Price',
    'dashboard.orderOpportunitySimulator.invalidPurchasePrice': 'Invalid Purchase Price',
    'dashboard.orderOpportunitySimulator.calculating': 'Calculating...',
    'dashboard.orderOpportunitySimulator.enterValuesPrompt': 'Please select a pair and enter amount to see simulation.',
    'dashboard.orderOpportunitySimulator.enterValuesPromptFull': 'Please select pair, enter amount, and purchase price to see simulation.',
    'dashboard.orderOpportunitySimulator.commissionInfo': 'Commission is {rate}% on the transaction value in {quote_currency}.',
    'dashboard.orderOpportunitySimulator.saveButton': 'Save Full Simulation',
    'dashboard.orderOpportunitySimulator.saveOrderButton': 'Save Order',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessTitle': 'Simulation Saved',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessDescription': 'Your simulation has been successfully saved.',
    'dashboard.orderOpportunitySimulator.toast.saveErrorTitle': 'Save Error',
    'dashboard.orderOpportunitySimulator.toast.saveErrorDescription': 'Could not save the simulation. Please try again.',
    'dashboard.orderOpportunitySimulator.toast.notLoggedInError': 'You must be logged in to save simulations/orders.',
    'dashboard.orderOpportunitySimulator.toast.noDataToSave': 'There is no valid simulation/order data to save.',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessTitle': 'Order Saved',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessDescription': 'The specific order has been successfully saved.',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorTitle': 'Order Save Error',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorDescription': 'Could not save the specific order. Please try again.',

    'dashboard.api.binance.fetchError': 'Failed to fetch prices from Binance: {status}',
    'dashboard.api.binance.errorTitle': 'Price Fetch Error (Binance)',
    'dashboard.api.binance.unknownError': 'Could not fetch live prices from Binance.',

    'dashboard.ai.errorTitle': 'AI Analysis Error',
    'dashboard.ai.errorDescription': 'Could not update AI trends.',
    'dashboard.ai.clientErrorReason': 'Client error fetching trend for {symbol}: {details}',
    'dashboard.ai.temporarilyDisabled': 'AI trend analysis is temporarily disabled.',
    'dashboard.websocket.errorTitle': 'WebSocket Error',
    'dashboard.websocket.errorDescriptionBinance': 'Connection to Binance live price feed failed. Falling back to periodic updates.',
    'dashboard.websocket.errorDescriptionBinanceFallback': 'Binance WebSocket failed. Using REST fallback.',
    'dashboard.websocket.errorMessage': 'Error message: {message}, Type: {type}',
    'dashboard.websocket.eventType': 'Event type: {type}',

    'history.page.title': "Order History",
    'history.menuItem': 'Order History',
    'history.filters.dateRange': "Date Range",
    'history.filters.startDate': "Start Date",
    'history.filters.endDate': "End Date",
    'history.filters.pickDate': "Pick a date",
    'history.filters.searchCrypto': "Search by Crypto",
    'history.filters.searchPlaceholder': "Enter crypto symbol (e.g., BTC)",
    'history.filters.resetButton': "Reset Filters",
    'history.export.csvButton': "Export to CSV",
    'history.export.pdfButton': "Export to PDF (Print)",
    'history.table.loading': "Loading order history...",
    'history.table.loadingError': "Failed to load order history.",
    'history.table.noOrders': "No orders found.",
    'history.table.header.timestamp': 'Date/Time',
    'history.table.header.originalPair': 'Pair',
    'history.table.header.targetCrypto': 'Target Crypto',
    'history.table.header.quoteCurrency': 'Quote',
    'history.table.header.buyAmount': 'Bought Amount',
    'history.table.header.buyPrice': 'Buy Price',
    'history.table.header.buyComm': 'Buy Comm.',
    'history.table.header.sellPrice': 'Sell Price',
    'history.table.header.sellComm': 'Sell Comm.',
    'history.table.header.netProfit': 'Net Profit',
    'history.toast.loadErrorTitle': 'Error',
    'history.toast.loadErrorDescription': 'Could not load order history.',
    'history.toast.noDataExportTitle': 'No Data',
    'history.toast.noDataExportDescription': 'There is no data to export.',
    'history.toast.csvExportSuccessTitle': 'Export Successful',
    'history.toast.csvExportSuccessDescription': 'Order history exported to CSV.',

    'balance.page.title': "Balance Overview",
    'balance.page.loading': 'Loading balance information...',
    'balance.menuItem': "Balance",
    'balance.filters.dateRange': "Date Range",
    'balance.filters.startDate': "Start Date",
    'balance.filters.endDate': "End Date",
    'balance.filters.pickDate': "Pick a date",
    'balance.filters.resetButton': "Reset Filters",
    'balance.summary.totalInvested': "Total Invested",
    'balance.summary.totalRecovered': "Total Recovered",
    'balance.summary.netResult': "Net Result",
    'balance.chart.title': "Profit/Loss Over Time", 
    'balance.chart.view.daily': "Daily",
    'balance.chart.view.monthly': "Monthly",
    'balance.chart.noData': "No order data available for the selected period.", 
    'balance.chart.profit': "Profit", 
    'balance.chart.loading': "Loading chart data...",
    'balance.loadingError': "Failed to load balance data from orders.",
    'balance.toast.loadErrorTitle': 'Error Loading Orders',
    'balance.toast.loadErrorDescription': 'Could not load order P/L data.',
    'balance.orderProfit.title': 'Order Profit/Loss Analysis',
    'balance.orderProfit.chart.title': 'Net Profit Over Time (from Orders)',

    'alertModal.title.edit': 'Edit Alert for {symbol}',
    'alertModal.title.create': 'Set Alert for {symbol}',
    'alertModal.description': 'Current price: ${price}',
    'alertModal.description.instruction': 'Get notified when the price goes above or below your target.',
    'alertModal.form.targetPriceLabel': 'Target Price (USDT)',
    'alertModal.form.targetPricePlaceholder': 'e.g., 50000',
    'alertModal.form.directionLabel': 'Notify me when price is',
    'alertModal.form.directionPlaceholder': 'Select direction',
    'alertModal.form.direction.above': 'Above',
    'alertModal.form.direction.below': 'Below',
    'alertModal.button.save': 'Set Alert',
    'alertModal.button.update': 'Update Alert',
    'alertModal.button.delete': 'Delete Alert',
    'alertModal.button.cancel': 'Cancel',
    'alertModal.toast.savedTitle': 'Alert Saved',
    'alertModal.toast.savedDescription': 'Your price alert for {symbol} has been set.',
    'alertModal.toast.updatedTitle': 'Alert Updated',
    'alertModal.toast.updatedDescription': 'Your price alert for {symbol} has been updated.',
    'alertModal.toast.deletedTitle': 'Alert Deleted',
    'alertModal.toast.deletedDescription': 'The price alert for {symbol} has been deleted.',
    'alertModal.toast.errorTitle': 'Error Saving Alert',
    'alertModal.toast.errorDescriptionGeneric': 'Could not save the alert.',
    'alertModal.toast.errorDeleteTitle': 'Error Deleting Alert',
    'alertModal.toast.errorDescriptionGenericDelete': 'Could not delete the alert.',

    'activeAlerts.title': 'My Price Alerts',
    'activeAlerts.description': 'Manage your active and inactive price alerts.',
    'activeAlerts.loading': 'Loading alerts...',
    'activeAlerts.noAlerts': 'You have no price alerts set up yet.',
    'activeAlerts.refreshButton': 'Refresh Alerts',
    'activeAlerts.confirmDelete': 'Are you sure you want to delete this alert for {symbol}?',
    'activeAlerts.table.symbol': 'Crypto',
    'activeAlerts.table.condition': 'Condition',
    'activeAlerts.table.status': 'Status',
    'activeAlerts.table.createdAt': 'Created',
    'activeAlerts.table.actions': 'Actions',
    'activeAlerts.table.directionAbove': '> ',
    'activeAlerts.table.directionBelow': '< ',
    'activeAlerts.table.statusActive': 'Active',
    'activeAlerts.table.statusInactive': 'Inactive',
    'activeAlerts.table.activateSwitch': 'Activate Alert',
    'activeAlerts.table.deactivateSwitch': 'Deactivate Alert',
    'activeAlerts.button.edit': 'Edit Alert',
    'activeAlerts.button.delete': 'Delete Alert',
    'activeAlerts.toast.fetchErrorTitle': 'Error',
    'activeAlerts.toast.fetchErrorDescription': 'Could not load your price alerts.',
    'activeAlerts.toast.deletedTitle': 'Alert Deleted',
    'activeAlerts.toast.deletedDescription': 'The alert for {symbol} has been removed.',
    'activeAlerts.toast.deleteErrorTitle': 'Error Deleting',
    'activeAlerts.toast.deleteErrorDescription': 'Could not delete the alert.',
    'activeAlerts.toast.activatedTitle': 'Alert Activated',
    'activeAlerts.toast.activatedDescription': 'The alert for {symbol} is now active.',
    'activeAlerts.toast.deactivatedTitle': 'Alert Deactivated',
    'activeAlerts.toast.deactivatedDescription': 'The alert for {symbol} is now inactive.',
    'activeAlerts.toast.toggleErrorTitle': 'Error Updating Alert',
    'activeAlerts.toast.toggleErrorDescription': 'Could not update alert status.',

    'zod.email.invalid': 'Invalid email address.',
    'zod.password.required': 'Password is required.',
    'zod.password.minLength': 'Password must be at least 8 characters.',
    'zod.password.lowercase': 'Password must contain at least one lowercase letter.',
    'zod.password.uppercase': 'Password must contain at least one uppercase letter.',
    'zod.password.number': 'Password must contain at least one number.',
    'zod.password.specialChar': 'Password must contain at least one special character.',
    'zod.password.confirmMatch': "Passwords don't match.",
    'zod.password.currentRequired': 'Current password is required.',
    'zod.password.newMinLength': 'New password must be at least 8 characters.',
    'zod.password.newLowercase': 'New password must contain at least one lowercase letter.',
    'zod.password.newUppercase': 'New password must contain at least one uppercase letter.',
    'zod.password.newNumber': 'New password must contain at least one number.',
    'zod.password.newSpecialChar': 'New password must contain at least one special character.',
    'zod.password.newConfirmMatch': "New passwords don't match.",
    'zod.orderOpportunity.selectPair': 'Please select a trading pair.',
    'zod.orderOpportunity.positiveInputAmount': 'Amount must be a positive number.',
    'zod.orderOpportunity.marketPricePositive': 'Market price must be a positive number.',
    'zod.orderOpportunity.purchasePriceUsdtPositive': 'Purchase price in USDT must be a positive number.',
    'zod.orderOpportunity.targetPricePositive': 'Target price must be a positive number.',
    'zod.alert.targetPricePositive': 'Target price must be a positive number.',
    'zod.alert.directionRequired': 'Please select a direction for the alert.',
    'footer.createdBy': 'Created with AI by Allan Soto',
  },
  es: {
    'app.name': 'SimulTradex',
    'app.loadingMessage': 'Cargando SimulTradex...',
    'settings.title': 'Configuración',
    'settings.myAccount': 'Mi Cuenta',
    'settings.accountSettings': 'Configuración de Cuenta',
    'settings.language': 'Idioma',
    'settings.logout': 'Cerrar Sesión',
    'header.userMenu.title': 'Menú de Usuario',
    'dashboard.title': 'Tablero',
    'dashboard.marketOverview': 'Resumen del Mercado',
    'dashboard.orderSimulator': 'Simulador de Órdenes',
    'dashboard.opportunitySimulator': 'Simulador de Oportunidades',
    'dashboard.loadingPrices': 'Cargando precios en vivo...',
    'dashboard.portfolioBalance': 'Balance de Portafolio',
    'dashboard.portfolioBalance.publicSourceMessage': "Mostrando datos de mercado de fuente pública.",
    'dashboard.connectionStatus.title': 'Problema de Conexión',
    'dashboard.connectionStatus.noFeed': 'Actualmente no se reciben actualizaciones de precios en vivo. Intentando conectar...',
    'dashboard.connectionStatus.fallbackTitle': 'Usando Conexión de Respaldo',
    'dashboard.connectionStatus.restFallbackActive': 'Falló la conexión WebSocket. Usando actualizaciones periódicas de API REST para precios.',
    'dashboard.cryptoCard.alertButton.title': 'Establecer Alerta de Precio',
    'dashboard.cryptoCard.alertButton.label': 'Crear Alerta',
    'dashboard.alerts.fetchErrorTitle': 'Error de Alertas',
    'dashboard.alerts.fetchErrorDescription': 'No se pudieron cargar sus alertas de precio activas.',
    'dashboard.alerts.triggeredTitle': '¡Alerta de Precio Activada!',
    'dashboard.alerts.triggeredDescription': '{symbol} ha alcanzado su precio objetivo de ${targetPrice}. Precio actual: ${currentPrice}.',
    'dashboard.ai.historicalDataError': 'No se pudieron obtener los datos históricos para {symbol}.',


    'login.title': 'Iniciar Sesión',
    'login.description': 'Inicia sesión en tu cuenta',
    'login.emailLabel': 'Correo Electrónico',
    'login.emailPlaceholder': 'tu@ejemplo.com',
    'login.passwordLabel': 'Contraseña',
    'login.submitButton': 'Iniciar Sesión',
    'login.signupPrompt': '¿No tienes una cuenta?',
    'login.signupLink': 'Regístrate',
    'login.error.invalidCredentials': 'Correo electrónico o contraseña no válidos.',
    'login.error.unknown': 'Ocurrió un error desconocido.',
    'login.error.passwordTooWeak': 'La contraseña no cumple los requisitos de seguridad. Debe tener más de 8 caracteres, incluir mayúsculas, minúsculas, un número y un símbolo.',
    'login.required': 'Por favor, inicia sesión para ver esta información.',
    'signup.title': 'Crear Cuenta',
    'signup.description': 'Crea tu cuenta',
    'signup.emailLabel': 'Correo Electrónico',
    'signup.emailPlaceholder': 'tu@ejemplo.com',
    'signup.passwordLabel': 'Contraseña',
    'signup.confirmPasswordLabel': 'Confirmar Contraseña',
    'signup.submitButton': 'Crear Cuenta',
    'signup.loginPrompt': '¿Ya tienes una cuenta?',
    'signup.loginLink': 'Iniciar Sesión',
    'signup.error.unknown': 'Ocurrió un error desconocido.',
    'signup.error.emailTaken': 'Este correo electrónico ya está registrado.',
    'signup.error.passwordTooWeak': 'La contraseña no cumple los requisitos de seguridad. Debe tener más de 8 caracteres, incluir mayúsculas, minúsculas, un número y un símbolo.',
    
    'account.passwordChange.title': "Cambiar Contraseña",
    'account.passwordChange.description': "Actualiza la contraseña de tu cuenta.",
    'account.passwordChange.currentPasswordLabel': "Contraseña Actual",
    'account.passwordChange.newPasswordLabel': "Nueva Contraseña",
    'account.passwordChange.confirmNewPasswordLabel': "Confirmar Nueva Contraseña",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "Cambiar Contraseña",
    'account.passwordChange.toast.changedTitle': "Contraseña Cambiada",
    'account.passwordChange.toast.changedDescription': "Tu contraseña ha sido actualizada exitosamente.",
    'account.passwordChange.toast.failedTitle': "Falló el Cambio de Contraseña",
    'account.passwordChange.toast.failedDescriptionIncorrect': "Contraseña actual incorrecta.",
    'account.passwordChange.toast.failedDescriptionWeak': 'La nueva contraseña no cumple los requisitos de seguridad.',

    'account.page.title': "Configuración de Cuenta",
    'account.page.userInfoTitle': "Información del Usuario",
    'account.page.emailLabel': "Correo Electrónico:",

    'dashboard.cryptoCard.tooltip.reason': "Razón:",
    'dashboard.cryptoCard.tooltip.confidence': "Confianza:",
    'dashboard.cryptoCard.trend.upward': "Tendencia alcista",
    'dashboard.cryptoCard.trend.downward': "Tendencia bajista",
    'dashboard.cryptoCard.trend.sideways': "Tendencia lateral",
    'dashboard.cryptoCard.trend.notAvailable': "Tendencia N/A",

    'dashboard.orderOpportunitySimulator.title': 'Simulador de Órdenes y Oportunidades',
    'dashboard.orderOpportunitySimulator.description': 'Simula un intercambio y visualiza oportunidades de venta potenciales con porcentajes de ganancia incrementales.',
    'dashboard.orderOpportunitySimulator.operationPairLabel': 'Par de Trading',
    'dashboard.orderOpportunitySimulator.inputAmountLabel': 'Cantidad ({currency})',
    'dashboard.orderOpportunitySimulator.purchasePriceUsdtLabel': 'Precio de Compra de {targetCrypto} (USDT)',
    'dashboard.orderOpportunitySimulator.marketPairPriceLabel': 'Precio de Mercado ({pair})',
    'dashboard.orderOpportunitySimulator.inputDivPurchasePriceLabel': 'Monto Entrada / Precio Compra',
    'dashboard.orderOpportunitySimulator.marketPriceDisplayLabel': 'Precio de Mercado ({cur2}/{cur1})',
    'dashboard.orderOpportunitySimulator.selectPairPlaceholder': 'Selecciona Par de Trading',
    'dashboard.orderOpportunitySimulator.table.header.operation': 'Operación',
    'dashboard.orderOpportunitySimulator.table.header.amountCur1Display': 'Cantidad ({currency1})',
    'dashboard.orderOpportunitySimulator.table.header.marketPriceDisplay': 'Precio de Mercado',
    'dashboard.orderOpportunitySimulator.table.header.amountCur2Display': 'Cantidad ({currency2})',
    'dashboard.orderOpportunitySimulator.table.header.commissionDisplay': 'Comisión ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.netProfitDisplay': 'Ganancia Neta ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.actions': 'Acciones',
    'dashboard.orderOpportunitySimulator.exchangeOperation': 'Intercambiar {cur1} por {cur2}',
    'dashboard.orderOpportunitySimulator.sellOperationPerc': 'Vender {targetCrypto} (+{perc}%)',
    'dashboard.orderOpportunitySimulator.priceUnavailable': 'Precio N/D',
    'dashboard.orderOpportunitySimulator.priceUnavailableShort': 'N/D',
    'dashboard.orderOpportunitySimulator.invalidMarketPrice': 'Precio de Mercado Inválido',
    'dashboard.orderOpportunitySimulator.invalidPurchasePrice': 'Precio de Compra Inválido',
    'dashboard.orderOpportunitySimulator.calculating': 'Calculando...',
    'dashboard.orderOpportunitySimulator.enterValuesPrompt': 'Por favor, selecciona un par e ingresa el monto para ver la simulación.',
    'dashboard.orderOpportunitySimulator.enterValuesPromptFull': 'Por favor, selecciona un par, ingresa el monto y el precio de compra para ver la simulación.',
    'dashboard.orderOpportunitySimulator.commissionInfo': 'La comisión es del {rate}% sobre el valor de la transacción en {quote_currency}.',
    'dashboard.orderOpportunitySimulator.saveButton': 'Guardar Simulación Completa',
    'dashboard.orderOpportunitySimulator.saveOrderButton': 'Guardar Orden',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessTitle': 'Simulación Guardada',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessDescription': 'Tu simulación ha sido guardada exitosamente.',
    'dashboard.orderOpportunitySimulator.toast.saveErrorTitle': 'Error al Guardar',
    'dashboard.orderOpportunitySimulator.toast.saveErrorDescription': 'No se pudo guardar la simulación. Por favor, inténtalo de nuevo.',
    'dashboard.orderOpportunitySimulator.toast.notLoggedInError': 'Debes iniciar sesión para guardar simulaciones/órdenes.',
    'dashboard.orderOpportunitySimulator.toast.noDataToSave': 'No hay datos de simulación/orden válidos para guardar.',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessTitle': 'Orden Guardada',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessDescription': 'La orden específica ha sido guardada exitosamente.',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorTitle': 'Error al Guardar Orden',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorDescription': 'No se pudo guardar la orden específica. Por favor, inténtalo de nuevo.',

    'dashboard.api.binance.fetchError': 'Error al obtener precios de Binance: {status}',
    'dashboard.api.binance.errorTitle': 'Error al Obtener Precios (Binance)',
    'dashboard.api.binance.unknownError': 'No se pudieron obtener los precios en vivo de Binance.',

    'dashboard.ai.errorTitle': 'Error en Análisis de IA',
    'dashboard.ai.errorDescription': 'No se pudieron actualizar las tendencias de IA.',
    'dashboard.ai.clientErrorReason': 'Error de cliente al obtener tendencia para {symbol}: {details}',
    'dashboard.ai.temporarilyDisabled': 'El análisis de tendencias de IA está temporalmente deshabilitado.',
    'dashboard.websocket.errorTitle': 'Error de WebSocket',
    'dashboard.websocket.errorDescriptionBinance': 'Falló la conexión al feed de precios en vivo de Binance. Cambiando a actualizaciones periódicas.',
    'dashboard.websocket.errorDescriptionBinanceFallback': 'Falló WebSocket de Binance. Usando API REST de respaldo.',
    'dashboard.websocket.errorMessage': 'Mensaje de error: {message}, Tipo: {type}',
    'dashboard.websocket.eventType': 'Tipo de evento: {type}',

    'history.page.title': "Historial de Órdenes",
    'history.menuItem': 'Historial de Órdenes',
    'history.filters.dateRange': "Rango de Fechas",
    'history.filters.startDate': "Fecha de Inicio",
    'history.filters.endDate': "Fecha de Fin",
    'history.filters.pickDate': "Elige una fecha",
    'history.filters.searchCrypto': "Buscar por Cripto",
    'history.filters.searchPlaceholder': "Ingresa símbolo (ej. BTC)",
    'history.filters.resetButton': "Limpiar Filtros",
    'history.export.csvButton': "Exportar a CSV",
    'history.export.pdfButton': "Exportar a PDF (Imprimir)",
    'history.table.loading': "Cargando historial de órdenes...",
    'history.table.loadingError': "Error al cargar el historial de órdenes.",
    'history.table.noOrders': "No se encontraron órdenes.",
    'history.table.header.timestamp': 'Fecha/Hora',
    'history.table.header.originalPair': 'Par',
    'history.table.header.targetCrypto': 'Cripto Obtenida',
    'history.table.header.quoteCurrency': 'Cotización',
    'history.table.header.buyAmount': 'Monto Comprado',
    'history.table.header.buyPrice': 'Precio Compra',
    'history.table.header.buyComm': 'Comis. Compra',
    'history.table.header.sellPrice': 'Precio Venta',
    'history.table.header.sellComm': 'Comis. Venta',
    'history.table.header.netProfit': 'Ganancia Neta',
    'history.toast.loadErrorTitle': 'Error',
    'history.toast.loadErrorDescription': 'No se pudo cargar el historial de órdenes.',
    'history.toast.noDataExportTitle': 'Sin Datos',
    'history.toast.noDataExportDescription': 'No hay datos para exportar.',
    'history.toast.csvExportSuccessTitle': 'Exportación Exitosa',
    'history.toast.csvExportSuccessDescription': 'Historial de órdenes exportado a CSV.',

    'balance.page.title': "Resumen de Balance",
    'balance.page.loading': 'Cargando información de balance...',
    'balance.menuItem': "Balance",
    'balance.orderProfit.title': 'Análisis de Ganancia/Pérdida por Órdenes',
    'balance.orderProfit.chart.title': 'Ganancia Neta en el Tiempo (de Órdenes)',

    'alertModal.title.edit': 'Editar Alerta para {symbol}',
    'alertModal.title.create': 'Crear Alerta para {symbol}',
    'alertModal.description': 'Precio actual: ${price}',
    'alertModal.description.instruction': 'Recibe una notificación cuando el precio supere o caiga por debajo de tu objetivo.',
    'alertModal.form.targetPriceLabel': 'Precio Objetivo (USDT)',
    'alertModal.form.targetPricePlaceholder': 'ej., 50000',
    'alertModal.form.directionLabel': 'Notificarme cuando el precio esté',
    'alertModal.form.directionPlaceholder': 'Seleccionar dirección',
    'alertModal.form.direction.above': 'Por encima de',
    'alertModal.form.direction.below': 'Por debajo de',
    'alertModal.button.save': 'Establecer Alerta',
    'alertModal.button.update': 'Actualizar Alerta',
    'alertModal.button.delete': 'Eliminar Alerta',
    'alertModal.button.cancel': 'Cancelar',
    'alertModal.toast.savedTitle': 'Alerta Guardada',
    'alertModal.toast.savedDescription': 'Tu alerta de precio para {symbol} ha sido establecida.',
    'alertModal.toast.updatedTitle': 'Alerta Actualizada',
    'alertModal.toast.updatedDescription': 'Tu alerta de precio para {symbol} ha sido actualizada.',
    'alertModal.toast.deletedTitle': 'Alerta Eliminada',
    'alertModal.toast.deletedDescription': 'La alerta de precio para {symbol} ha sido eliminada.',
    'alertModal.toast.errorTitle': 'Error al Guardar Alerta',
    'alertModal.toast.errorDescriptionGeneric': 'No se pudo guardar la alerta.',
    'alertModal.toast.errorDeleteTitle': 'Error al Eliminar Alerta',
    'alertModal.toast.errorDescriptionGenericDelete': 'No se pudo eliminar la alerta.',

    'activeAlerts.title': 'Mis Alertas de Precio',
    'activeAlerts.description': 'Gestiona tus alertas de precio activas e inactivas.',
    'activeAlerts.loading': 'Cargando alertas...',
    'activeAlerts.noAlerts': 'Aún no has configurado ninguna alerta de precio.',
    'activeAlerts.refreshButton': 'Refrescar Alertas',
    'activeAlerts.confirmDelete': '¿Estás seguro de que quieres eliminar esta alerta para {symbol}?',
    'activeAlerts.table.symbol': 'Cripto',
    'activeAlerts.table.condition': 'Condición',
    'activeAlerts.table.status': 'Estado',
    'activeAlerts.table.createdAt': 'Creada',
    'activeAlerts.table.actions': 'Acciones',
    'activeAlerts.table.directionAbove': '> ',
    'activeAlerts.table.directionBelow': '< ',
    'activeAlerts.table.statusActive': 'Activa',
    'activeAlerts.table.statusInactive': 'Inactiva',
    'activeAlerts.table.activateSwitch': 'Activar Alerta',
    'activeAlerts.table.deactivateSwitch': 'Desactivar Alerta',
    'activeAlerts.button.edit': 'Editar Alerta',
    'activeAlerts.button.delete': 'Eliminar Alerta',
    'activeAlerts.toast.fetchErrorTitle': 'Error',
    'activeAlerts.toast.fetchErrorDescription': 'No se pudieron cargar tus alertas de precio.',
    'activeAlerts.toast.deletedTitle': 'Alerta Eliminada',
    'activeAlerts.toast.deletedDescription': 'La alerta para {symbol} ha sido eliminada.',
    'activeAlerts.toast.deleteErrorTitle': 'Error al Eliminar',
    'activeAlerts.toast.deleteErrorDescription': 'No se pudo eliminar la alerta.',
    'activeAlerts.toast.activatedTitle': 'Alerta Activada',
    'activeAlerts.toast.activatedDescription': 'La alerta para {symbol} ahora está activa.',
    'activeAlerts.toast.deactivatedTitle': 'Alerta Desactivada',
    'activeAlerts.toast.deactivatedDescription': 'La alerta para {symbol} ahora está inactiva.',
    'activeAlerts.toast.toggleErrorTitle': 'Error al Actualizar Alerta',
    'activeAlerts.toast.toggleErrorDescription': 'No se pudo actualizar el estado de la alerta.',

     'zod.email.invalid': 'Dirección de correo electrónico no válida.',
    'zod.password.required': 'La contraseña es obligatoria.',
    'zod.password.minLength': 'La contraseña debe tener al menos 8 caracteres.',
    'zod.password.lowercase': 'La contraseña debe contener al menos una letra minúscula.',
    'zod.password.uppercase': 'La contraseña debe contener al menos una letra mayúscula.',
    'zod.password.number': 'La contraseña debe contener al menos un número.',
    'zod.password.specialChar': 'La contraseña debe contener al menos un carácter especial.',
    'zod.password.confirmMatch': 'Las contraseñas no coinciden.',
    'zod.password.currentRequired': 'La contraseña actual es obligatoria.',
    'zod.password.newMinLength': 'La contraseña nueva debe tener al menos 8 caracteres.',
    'zod.password.newLowercase': 'La contraseña nueva debe contener al menos una letra minúscula.',
    'zod.password.newUppercase': 'La contraseña nueva debe contener al menos una letra mayúscula.',
    'zod.password.newNumber': 'La contraseña nueva debe contener al menos un número.',
    'zod.password.newSpecialChar': 'La contraseña nueva debe contener al menos un carácter especial.',
    'zod.password.newConfirmMatch': 'Las contraseñas nuevas no coinciden.',
    'zod.orderOpportunity.selectPair': 'Por favor selecciona un par de trading.',
    'zod.orderOpportunity.positiveInputAmount': 'El monto debe ser un número positivo.',
    'zod.orderOpportunity.marketPricePositive': 'El precio de mercado debe ser un número positivo.',
    'zod.orderOpportunity.purchasePriceUsdtPositive': 'El precio de compra en USDT debe ser un número positivo.',
    'zod.orderOpportunity.targetPricePositive': 'El precio objetivo debe ser un número positivo.',
    'zod.alert.targetPricePositive': 'El precio objetivo debe ser un número positivo.',
    'zod.alert.directionRequired': 'Por favor, selecciona una dirección para la alerta.',
    'footer.createdBy': 'Creado con IA por Allan Soto',
  },
  fr: { 
    'app.name': 'SimulTradex',
    'app.loadingMessage': 'Chargement de SimulTradex...',
    'settings.title': 'Paramètres',
    'settings.myAccount': 'Mon Compte',
    'settings.accountSettings': 'Paramètres du Compte',
    'settings.language': 'Langue',
    'settings.logout': 'Se Déconnecter',
    'header.userMenu.title': 'Menu Utilisateur',
    'dashboard.title': 'Tableau de Bord',
    'dashboard.marketOverview': 'Aperçu du Marché',
    'dashboard.loadingPrices': 'Chargement des prix en direct...',
    'dashboard.portfolioBalance': 'Solde du Portefeuille',
    'dashboard.portfolioBalance.publicSourceMessage': "Affichage des données de marché à partir d'une source publique.",
    'dashboard.connectionStatus.title': 'Problème de Connexion',
    'dashboard.connectionStatus.noFeed': 'Actuellement, aucune mise à jour des prix en direct n\'est reçue. Tentative de connexion...',
    'dashboard.connectionStatus.fallbackTitle': 'Utilisation de la Connexion de Secours',
    'dashboard.connectionStatus.restFallbackActive': 'Échec de la connexion WebSocket. Utilisation des mises à jour périodiques de l\'API REST pour les prix.',
    'dashboard.cryptoCard.alertButton.title': 'Définir une Alerte de Prix',
    'dashboard.cryptoCard.alertButton.label': 'Créer Alerte',
    'dashboard.alerts.fetchErrorTitle': 'Erreur d\'Alertes',
    'dashboard.alerts.fetchErrorDescription': 'Impossible de charger vos alertes de prix actives.',
    'dashboard.alerts.triggeredTitle': 'Alerte de Prix Déclenchée !',
    'dashboard.alerts.triggeredDescription': '{symbol} a atteint votre prix cible de ${targetPrice}. Prix actuel : ${currentPrice}.',
    'dashboard.ai.historicalDataError': 'Impossible de récupérer les données historiques pour {symbol}.',

    'login.title': 'Se Connecter',
    'login.description': 'Connectez-vous à votre compte',
    'login.emailLabel': 'E-mail',
    'login.emailPlaceholder': 'vous@example.com',
    'login.passwordLabel': 'Mot de passe',
    'login.submitButton': 'Se Connecter',
    'login.signupPrompt': 'Vous n\'avez pas de compte ?',
    'login.signupLink': 'S\'inscrire',
    'login.error.invalidCredentials': 'Email ou mot de passe incorrect.',
    'login.error.unknown': 'Une erreur inconnue est survenue.',
    'login.error.passwordTooWeak': 'Le mot de passe ne respecte pas les exigences de sécurité. Il doit comporter au moins 8 caractères, inclure une majuscule, une minuscule, un chiffre et un symbole.',
    'login.required': 'Veuillez vous connecter pour voir ces informations.',

    'signup.title': 'S\'inscrire',
    'signup.description': 'Créez votre compte',
    'signup.emailLabel': 'E-mail',
    'signup.emailPlaceholder': 'vous@example.com',
    'signup.passwordLabel': 'Mot de passe',
    'signup.confirmPasswordLabel': 'Confirmer le mot de passe',
    'signup.submitButton': 'S\'inscrire',
    'signup.loginPrompt': 'Vous avez déjà un compte ?',
    'signup.loginLink': 'Se connecter',
    'signup.error.emailTaken': 'Cet e-mail est déjà enregistré.',
    'signup.error.unknown': 'Une erreur inconnue est survenue.',
    'signup.error.passwordTooWeak': 'Le mot de passe ne respecte pas les exigences de sécurité. Il doit comporter au moins 8 caractères, inclure une majuscule, une minuscule, un chiffre et un symbole.',
    
    'account.passwordChange.title': "Changer le Mot de Passe",
    'account.passwordChange.description': "Mettez à jour le mot de passe de votre compte.",
    'account.passwordChange.currentPasswordLabel': "Mot de Passe Actuel",
    'account.passwordChange.newPasswordLabel': "Nouveau Mot de Passe",
    'account.passwordChange.confirmNewPasswordLabel': "Confirmer le Nouveau Mot de Passe",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "Changer le Mot de Passe",
    'account.passwordChange.toast.changedTitle': "Mot de Passe Changé",
    'account.passwordChange.toast.changedDescription': "Votre mot de passe a été mis à jour avec succès.",
    'account.passwordChange.toast.failedTitle': "Échec du Changement de Mot de Passe",
    'account.passwordChange.toast.failedDescriptionIncorrect': "Mot de passe actuel incorrect.",
    'account.passwordChange.toast.failedDescriptionWeak': 'Le nouveau mot de passe ne répond pas aux exigences de sécurité.',

    'account.page.title': "Paramètres du Compte",
    'account.page.userInfoTitle': "Informations Utilisateur",
    'account.page.emailLabel': "E-mail :",

    'dashboard.cryptoCard.tooltip.reason': "Raison :",
    'dashboard.cryptoCard.tooltip.confidence': "Confiance :",
    'dashboard.cryptoCard.trend.upward': "Tendance haussière",
    'dashboard.cryptoCard.trend.downward': "Tendance baissière",
    'dashboard.cryptoCard.trend.sideways': "Tendance latérale",
    'dashboard.cryptoCard.trend.notAvailable': "Tendance N/A",

    'dashboard.orderOpportunitySimulator.title': 'Simulateur d\'Ordres et d\'Opportunités',
    'dashboard.orderOpportunitySimulator.description': 'Simulez un échange et visualisez les opportunités de vente potentielles avec des pourcentages de profit incrémentiels.',
    'dashboard.orderOpportunitySimulator.operationPairLabel': 'Paire de Trading',
    'dashboard.orderOpportunitySimulator.inputAmountLabel': 'Montant ({currency})',
    'dashboard.orderOpportunitySimulator.purchasePriceUsdtLabel': 'Prix d\'Achat de {targetCrypto} (USDT)',
    'dashboard.orderOpportunitySimulator.marketPairPriceLabel': 'Prix du Marché ({pair})',
    'dashboard.orderOpportunitySimulator.inputDivPurchasePriceLabel': 'Montant Entrée / Prix Achat',
    'dashboard.orderOpportunitySimulator.marketPriceDisplayLabel': 'Prix du Marché ({cur2}/{cur1})',
    'dashboard.orderOpportunitySimulator.selectPairPlaceholder': 'Sélectionner Paire de Trading',
    'dashboard.orderOpportunitySimulator.table.header.operation': 'Opération',
    'dashboard.orderOpportunitySimulator.table.header.amountCur1Display': 'Montant ({currency1})',
    'dashboard.orderOpportunitySimulator.table.header.marketPriceDisplay': 'Prix du Marché',
    'dashboard.orderOpportunitySimulator.table.header.amountCur2Display': 'Montant ({currency2})',
    'dashboard.orderOpportunitySimulator.table.header.commissionDisplay': 'Commission ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.netProfitDisplay': 'Profit Net ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.actions': 'Actions',
    'dashboard.orderOpportunitySimulator.exchangeOperation': 'Échanger {cur1} contre {cur2}',
    'dashboard.orderOpportunitySimulator.sellOperationPerc': 'Vendre {targetCrypto} (+{perc}%)',
    'dashboard.orderOpportunitySimulator.priceUnavailable': 'Prix N/A',
    'dashboard.orderOpportunitySimulator.priceUnavailableShort': 'N/A',
    'dashboard.orderOpportunitySimulator.invalidMarketPrice': 'Prix du Marché Invalide',
    'dashboard.orderOpportunitySimulator.invalidPurchasePrice': 'Prix d\'Achat Invalide',
    'dashboard.orderOpportunitySimulator.calculating': 'Calcul en cours...',
    'dashboard.orderOpportunitySimulator.enterValuesPrompt': 'Veuillez sélectionner une paire et entrer le montant pour voir la simulation.',
    'dashboard.orderOpportunitySimulator.enterValuesPromptFull': 'Veuillez sélectionner une paire, entrer le montant et le prix d\'achat pour voir la simulation.',
    'dashboard.orderOpportunitySimulator.commissionInfo': 'La commission est de {rate}% sur la valeur de la transaction en {quote_currency}.',
    'dashboard.orderOpportunitySimulator.saveButton': 'Sauvegarder Simulation Complète',
    'dashboard.orderOpportunitySimulator.saveOrderButton': 'Sauvegarder l\'Ordre',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessTitle': 'Simulation Sauvegardée',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessDescription': 'Votre simulation a été sauvegardée avec succès.',
    'dashboard.orderOpportunitySimulator.toast.saveErrorTitle': 'Erreur de Sauvegarde',
    'dashboard.orderOpportunitySimulator.toast.saveErrorDescription': 'Impossible de sauvegarder la simulation. Veuillez réessayer.',
    'dashboard.orderOpportunitySimulator.toast.notLoggedInError': 'Vous devez être connecté pour sauvegarder les simulations/ordres.',
    'dashboard.orderOpportunitySimulator.toast.noDataToSave': 'Aucune donnée de simulation/ordre valide à sauvegarder.',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessTitle': 'Ordre Sauvegardé',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessDescription': 'L\'ordre spécifique a été sauvegardé avec succès.',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorTitle': 'Erreur de Sauvegarde d\'Ordre',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorDescription': 'Impossible de sauvegarder l\'ordre spécifique. Veuillez réessayer.',

    'dashboard.api.binance.fetchError': 'Échec de la récupération des prix de Binance : {status}',
    'dashboard.api.binance.errorTitle': 'Erreur de Récupération des Prix (Binance)',
    'dashboard.api.binance.unknownError': 'Impossible de récupérer les prix en direct de Binance.',

    'dashboard.ai.errorTitle': 'Erreur d\'Analyse IA',
    'dashboard.ai.errorDescription': 'Impossible de mettre à jour les tendances IA.',
    'dashboard.ai.clientErrorReason': 'Erreur client lors de la récupération de la tendance pour {symbol} : {details}',
    'dashboard.ai.temporarilyDisabled': 'L\'analyse des tendances IA est temporairement désactivée.',
    'dashboard.websocket.errorTitle': 'Erreur WebSocket',
    'dashboard.websocket.errorDescriptionBinance': 'Échec de la connexion au flux de prix en direct de Binance. Passage aux mises à jour périodiques.',
    'dashboard.websocket.errorDescriptionBinanceFallback': 'Échec du WebSocket Binance. Utilisation de l\'API REST de secours.',
    'dashboard.websocket.errorMessage': 'Message d\'erreur : {message}, Type : {type}',
    'dashboard.websocket.eventType': 'Type d\'événement : {type}',

    'history.page.title': "Historique des Ordres",
    'history.menuItem': 'Historique des Ordres',
    'history.filters.dateRange': "Plage de Dates",
    'history.filters.startDate': "Date de Début",
    'history.filters.endDate': "Date de Fin",
    'history.filters.pickDate': "Choisir une date",
    'history.filters.searchCrypto': "Rechercher par Crypto",
    'history.filters.searchPlaceholder': "Entrer symbole (ex. BTC)",
    'history.filters.resetButton': "Réinitialiser Filtres",
    'history.export.csvButton': "Exporter en CSV",
    'history.export.pdfButton': "Exporter en PDF (Imprimer)",
    'history.table.loading': "Chargement de l'historique des ordres...",
    'history.table.loadingError': "Erreur lors du chargement de l'historique des ordres.",
    'history.table.noOrders': "Aucun ordre trouvé.",
    'history.table.header.timestamp': 'Date/Heure',
    'history.table.header.originalPair': 'Paire',
    'history.table.header.targetCrypto': 'Crypto Cible',
    'history.table.header.quoteCurrency': 'Devise',
    'history.table.header.buyAmount': 'Montant Acheté',
    'history.table.header.buyPrice': 'Prix d\'Achat',
    'history.table.header.buyComm': 'Comm. Achat',
    'history.table.header.sellPrice': 'Prix de Vente',
    'history.table.header.sellComm': 'Comm. Vente',
    'history.table.header.netProfit': 'Profit Net',
    'history.toast.loadErrorTitle': 'Erreur',
    'history.toast.loadErrorDescription': 'Impossible de charger l\'historique des ordres.',
    'history.toast.noDataExportTitle': 'Aucune Donnée',
    'history.toast.noDataExportDescription': 'Aucune donnée à exporter.',
    'history.toast.csvExportSuccessTitle': 'Exportation Réussie',
    'history.toast.csvExportSuccessDescription': 'Historique des ordres exporté en CSV.',

    'balance.page.title': "Aperçu du Solde",
    'balance.page.loading': 'Chargement des informations du solde...',
    'balance.menuItem': "Solde",
    'balance.orderProfit.title': 'Analyse des Profits/Pertes sur Ordres',
    'balance.orderProfit.chart.title': 'Bénéfice Net au Fil du Temps (des Ordres)',

    'alertModal.title.edit': 'Modifier l\'Alerte pour {symbol}',
    'alertModal.title.create': 'Définir une Alerte pour {symbol}',
    'alertModal.description': 'Prix actuel : ${price}',
    'alertModal.description.instruction': 'Soyez notifié lorsque le prix dépasse ou descend en dessous de votre cible.',
    'alertModal.form.targetPriceLabel': 'Prix Cible (USDT)',
    'alertModal.form.targetPricePlaceholder': 'ex., 50000',
    'alertModal.form.directionLabel': 'Me notifier quand le prix est',
    'alertModal.form.directionPlaceholder': 'Sélectionner la direction',
    'alertModal.form.direction.above': 'Au-dessus de',
    'alertModal.form.direction.below': 'En dessous de',
    'alertModal.button.save': 'Définir l\'Alerte',
    'alertModal.button.update': 'Mettre à Jour l\'Alerte',
    'alertModal.button.delete': 'Supprimer l\'Alerte',
    'alertModal.button.cancel': 'Annuler',
    'alertModal.toast.savedTitle': 'Alerte Enregistrée',
    'alertModal.toast.savedDescription': 'Votre alerte de prix pour {symbol} a été définie.',
    'alertModal.toast.updatedTitle': 'Alerte Mise à Jour',
    'alertModal.toast.updatedDescription': 'Votre alerte de prix pour {symbol} a été mise à jour.',
    'alertModal.toast.deletedTitle': 'Alerte Supprimée',
    'alertModal.toast.deletedDescription': 'L\'alerte de prix pour {symbol} a été supprimée.',
    'alertModal.toast.errorTitle': 'Erreur d\'Enregistrement de l\'Alerte',
    'alertModal.toast.errorDescriptionGeneric': 'Impossible d\'enregistrer l\'alerte.',
    'alertModal.toast.errorDeleteTitle': 'Erreur de Suppression de l\'Alerte',
    'alertModal.toast.errorDescriptionGenericDelete': 'Impossible de supprimer l\'alerte.',

    'activeAlerts.title': 'Mes Alertes de Prix',
    'activeAlerts.description': 'Gérez vos alertes de prix actives et inactives.',
    'activeAlerts.loading': 'Chargement des alertes...',
    'activeAlerts.noAlerts': 'Vous n\'avez pas encore configuré d\'alertes de prix.',
    'activeAlerts.refreshButton': 'Rafraîchir les Alertes',
    'activeAlerts.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette alerte pour {symbol} ?',
    'activeAlerts.table.symbol': 'Crypto',
    'activeAlerts.table.condition': 'Condition',
    'activeAlerts.table.status': 'Statut',
    'activeAlerts.table.createdAt': 'Créée le',
    'activeAlerts.table.actions': 'Actions',
    'activeAlerts.table.directionAbove': '> ',
    'activeAlerts.table.directionBelow': '< ',
    'activeAlerts.table.statusActive': 'Active',
    'activeAlerts.table.statusInactive': 'Inactive',
    'activeAlerts.table.activateSwitch': 'Activer l\'Alerte',
    'activeAlerts.table.deactivateSwitch': 'Désactiver l\'Alerte',
    'activeAlerts.button.edit': 'Modifier l\'Alerte',
    'activeAlerts.button.delete': 'Supprimer l\'Alerte',
    'activeAlerts.toast.fetchErrorTitle': 'Erreur',
    'activeAlerts.toast.fetchErrorDescription': 'Impossible de charger vos alertes de prix.',
    'activeAlerts.toast.deletedTitle': 'Alerte Supprimée',
    'activeAlerts.toast.deletedDescription': 'L\'alerte pour {symbol} a été supprimée.',
    'activeAlerts.toast.deleteErrorTitle': 'Erreur de Suppression',
    'activeAlerts.toast.deleteErrorDescription': 'Impossible de supprimer l\'alerte.',
    'activeAlerts.toast.activatedTitle': 'Alerte Activée',
    'activeAlerts.toast.activatedDescription': 'L\'alerte pour {symbol} est maintenant active.',
    'activeAlerts.toast.deactivatedTitle': 'Alerte Désactivée',
    'activeAlerts.toast.deactivatedDescription': 'L\'alerte pour {symbol} est maintenant inactive.',
    'activeAlerts.toast.toggleErrorTitle': 'Erreur de Mise à Jour de l\'Alerte',
    'activeAlerts.toast.toggleErrorDescription': 'Impossible de mettre à jour le statut de l\'alerte.',

     'zod.email.invalid': 'Adresse e-mail invalide.',
    'zod.password.required': 'Le mot de passe est requis.',
    'zod.password.minLength': 'Le mot de passe doit comporter au moins 8 caractères.',
    'zod.password.lowercase': 'Le mot de passe doit contenir au moins une lettre minuscule.',
    'zod.password.uppercase': 'Le mot de passe doit contenir au moins une lettre majuscule.',
    'zod.password.number': 'Le mot de passe doit contenir au moins un chiffre.',
    'zod.password.specialChar': 'Le mot de passe doit contenir au moins un caractère spécial.',
    'zod.password.confirmMatch': 'Les mots de passe ne correspondent pas.',
    'zod.password.currentRequired': 'Le mot de passe actuel est requis.',
    'zod.password.newMinLength': 'Le nouveau mot de passe doit comporter au moins 8 caractères.',
    'zod.password.newLowercase': 'Le nouveau mot de passe doit contenir au moins une lettre minuscule.',
    'zod.password.newUppercase': 'Le nouveau mot de passe doit contenir au moins une lettre majuscule.',
    'zod.password.newNumber': 'Le nouveau mot de passe doit contenir au moins un chiffre.',
    'zod.password.newSpecialChar': 'Le nouveau mot de passe doit contenir au moins un caractère spécial.',
    'zod.password.newConfirmMatch': 'Les nouveaux mots de passe ne correspondent pas.',
    'zod.orderOpportunity.selectPair': 'Veuillez sélectionner une paire de trading.',
    'zod.orderOpportunity.positiveInputAmount': 'Le montant doit être un nombre positif.',
    'zod.orderOpportunity.marketPricePositive': 'Le prix du marché doit être un nombre positif.',
    'zod.orderOpportunity.purchasePriceUsdtPositive': 'Le prix d\'achat en USDT doit être un nombre positif.',
    'zod.orderOpportunity.targetPricePositive': 'Le prix cible doit être un nombre positif.',
    'zod.alert.targetPricePositive': 'Le prix cible doit être un nombre positif.',
    'zod.alert.directionRequired': 'Veuillez sélectionner une direction pour l\'alerte.',
    'footer.createdBy': 'Créé avec IA par Allan Soto',
  },
  hi: { 
    'app.name': 'सिमुलट्रेडेक्स',
    'app.loadingMessage': 'सिमुलट्रेडेक्स लोड हो रहा है...',
    'settings.title': 'सेटिंग्स',
    'settings.myAccount': 'मेरा खाता',
    'settings.accountSettings': 'खाता सेटिंग्स',
    'settings.language': 'भाषा',
    'settings.logout': 'लॉग आउट करें',
    'header.userMenu.title': 'उपयोगकर्ता मेनू',
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.marketOverview': 'बाज़ार अवलोकन',
    'dashboard.loadingPrices': 'लाइव कीमतें लोड हो रही हैं...',
    'dashboard.portfolioBalance': 'पोर्टफोलियो बैलेंस',
    'dashboard.portfolioBalance.publicSourceMessage': "सार्वजनिक स्रोत से बाजार डेटा प्रदर्शित हो रहा है।",
    'dashboard.connectionStatus.title': 'कनेक्शन समस्या',
    'dashboard.connectionStatus.noFeed': 'वर्तमान में लाइव मूल्य अपडेट प्राप्त नहीं हो रहे हैं। कनेक्ट करने का प्रयास किया जा रहा है...',
    'dashboard.connectionStatus.fallbackTitle': 'फॉल बैक कनेक्शन का उपयोग किया जा रहा है',
    'dashboard.connectionStatus.restFallbackActive': 'वेबसॉकेट कनेक्शन विफल। कीमतों के लिए आवधिक REST API अपडेट का उपयोग किया जा रहा है।',
    'dashboard.cryptoCard.alertButton.title': 'मूल्य चेतावनी सेट करें',
    'dashboard.cryptoCard.alertButton.label': 'चेतावनी सेट करें',
    'dashboard.alerts.fetchErrorTitle': 'चेतावनी त्रुटि',
    'dashboard.alerts.fetchErrorDescription': 'आपकी सक्रिय मूल्य चेतावनियां लोड नहीं की जा सकीं।',
    'dashboard.alerts.triggeredTitle': 'मूल्य चेतावनी सक्रिय!',
    'dashboard.alerts.triggeredDescription': '{symbol} आपके लक्ष्य मूल्य ${targetPrice} पर पहुंच गया है। वर्तमान मूल्य: ${currentPrice}।',
    'dashboard.ai.historicalDataError': '{symbol} के लिए ऐतिहासिक डेटा प्राप्त नहीं किया जा सका।',


    'login.title': 'लॉग इन करें',
    'login.description': 'अपने खाते में लॉग इन करें',
    'login.emailLabel': 'ईमेल',
    'login.emailPlaceholder': 'aap@udaharan.com',
    'login.passwordLabel': 'पासवर्ड',
    'login.submitButton': 'लॉग इन करें',
    'login.signupPrompt': 'खाता नहीं है?',
    'login.signupLink': 'साइन अप करें',
    'login.error.invalidCredentials': 'अमान्य ईमेल या पासवर्ड।',
    'login.error.unknown': 'एक अज्ञात त्रुटि हुई।',
    'login.error.passwordTooWeak': 'पासवर्ड सुरक्षा आवश्यकताओं को पूरा नहीं करता है। इसमें 8+ वर्ण होने चाहिए, जिसमें अपरकेस, लोअरकेस, संख्या और प्रतीक शामिल हों।',
    'login.required': 'कृपया यह जानकारी देखने के लिए लॉग इन करें।',

    'signup.title': 'साइन अप करें',
    'signup.description': 'अपना खाता बनाएं',
    'signup.emailLabel': 'ईमेल',
    'signup.emailPlaceholder': 'aap@udaharan.com',
    'signup.passwordLabel': 'पासवर्ड',
    'signup.confirmPasswordLabel': 'पासवर्ड की पुष्टि करें',
    'signup.submitButton': 'साइन अप करें',
    'signup.loginPrompt': 'पहले से ही एक खाता है?',
    'signup.loginLink': 'लॉग इन करें',
    'signup.error.emailTaken': 'यह ईमेल पहले से पंजीकृत है।',
    'signup.error.unknown': 'एक अज्ञात त्रुटि हुई।',
    'signup.error.passwordTooWeak': 'पासवर्ड सुरक्षा आवश्यकताओं को पूरा नहीं करता है। इसमें 8+ वर्ण होने चाहिए, जिसमें अपरकेस, लोअरकेस, संख्या और प्रतीक शामिल हों।',
    
    'account.passwordChange.title': "पासवर्ड बदलें",
    'account.passwordChange.description': "अपना खाता पासवर्ड अपडेट करें।",
    'account.passwordChange.currentPasswordLabel': "वर्तमान पासवर्ड",
    'account.passwordChange.newPasswordLabel': "नया पासवर्ड",
    'account.passwordChange.confirmNewPasswordLabel': "नए पासवर्ड की पुष्टि करें",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "पासवर्ड बदलें",
    'account.passwordChange.toast.changedTitle': "पासवर्ड बदला गया",
    'account.passwordChange.toast.changedDescription': "आपका पासवर्ड सफलतापूर्वक अपडेट कर दिया गया है।",
    'account.passwordChange.toast.failedTitle': "पासवर्ड बदलने में विफल",
    'account.passwordChange.toast.failedDescriptionIncorrect': "गलत वर्तमान पासवर्ड।",
    'account.passwordChange.toast.failedDescriptionWeak': 'नया पासवर्ड सुरक्षा आवश्यकताओं को पूरा नहीं करता है।',

    'account.page.title': "खाता सेटिंग्स",
    'account.page.userInfoTitle': "उपयोगकर्ता जानकारी",
    'account.page.emailLabel': "ईमेल:",

    'dashboard.cryptoCard.tooltip.reason': "कारण:",
    'dashboard.cryptoCard.tooltip.confidence': "आत्मविश्वास:",
    'dashboard.cryptoCard.trend.upward': "ऊपर की ओर प्रवृत्ति",
    'dashboard.cryptoCard.trend.downward': "नीचे की ओर प्रवृत्ति",
    'dashboard.cryptoCard.trend.sideways': "बग़ल में प्रवृत्ति",
    'dashboard.cryptoCard.trend.notAvailable': "प्रवृत्ति उपलब्ध नहीं है",

    'dashboard.orderOpportunitySimulator.title': 'ऑर्डर और अवसर सिम्युलेटर',
    'dashboard.orderOpportunitySimulator.description': 'एक एक्सचेंज का अनुकरण करें और वृद्धिशील लाभ प्रतिशत पर संभावित बिक्री के अवसर देखें।',
    'dashboard.orderOpportunitySimulator.operationPairLabel': 'ट्रेडिंग जोड़ी',
    'dashboard.orderOpportunitySimulator.inputAmountLabel': 'राशि ({currency})',
    'dashboard.orderOpportunitySimulator.purchasePriceUsdtLabel': '{targetCrypto} की खरीद मूल्य (USDT)',
    'dashboard.orderOpportunitySimulator.marketPairPriceLabel': 'बाजार मूल्य ({pair})',
    'dashboard.orderOpportunitySimulator.inputDivPurchasePriceLabel': 'इनपुट राशि / खरीद मूल्य',
    'dashboard.orderOpportunitySimulator.marketPriceDisplayLabel': 'बाजार मूल्य ({cur2}/{cur1})',
    'dashboard.orderOpportunitySimulator.selectPairPlaceholder': 'ट्रेडिंग जोड़ी चुनें',
    'dashboard.orderOpportunitySimulator.table.header.operation': 'ऑपरेशन',
    'dashboard.orderOpportunitySimulator.table.header.amountCur1Display': 'राशि ({currency1})',
    'dashboard.orderOpportunitySimulator.table.header.marketPriceDisplay': 'बाजार मूल्य',
    'dashboard.orderOpportunitySimulator.table.header.amountCur2Display': 'राशि ({currency2})',
    'dashboard.orderOpportunitySimulator.table.header.commissionDisplay': 'कमीशन ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.netProfitDisplay': 'शुद्ध लाभ ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.actions': 'कार्रवाई',
    'dashboard.orderOpportunitySimulator.exchangeOperation': '{cur1} को {cur2} से एक्सचेंज करें',
    'dashboard.orderOpportunitySimulator.sellOperationPerc': '{targetCrypto} बेचें (+{perc}%)',
    'dashboard.orderOpportunitySimulator.priceUnavailable': 'मूल्य उपलब्ध नहीं',
    'dashboard.orderOpportunitySimulator.priceUnavailableShort': 'उपलब्ध नहीं',
    'dashboard.orderOpportunitySimulator.invalidMarketPrice': 'अमान्य बाजार मूल्य',
    'dashboard.orderOpportunitySimulator.invalidPurchasePrice': 'अमान्य खरीद मूल्य',
    'dashboard.orderOpportunitySimulator.calculating': 'गणना की जा रही है...',
    'dashboard.orderOpportunitySimulator.enterValuesPrompt': 'कृपया एक जोड़ी चुनें और अनुकरण देखने के लिए राशि दर्ज करें।',
    'dashboard.orderOpportunitySimulator.enterValuesPromptFull': 'कृपया जोड़ी चुनें, राशि दर्ज करें, और अनुकरण देखने के लिए खरीद मूल्य दर्ज करें।',
    'dashboard.orderOpportunitySimulator.commissionInfo': 'कमीशन {quote_currency} में लेनदेन मूल्य का {rate}% है।',
    'dashboard.orderOpportunitySimulator.saveButton': 'पूर्ण अनुकरण सहेजें',
    'dashboard.orderOpportunitySimulator.saveOrderButton': 'ऑर्डर सहेजें',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessTitle': 'अनुकरण सहेजा गया',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessDescription': 'आपका अनुकरण सफलतापूर्वक सहेजा गया है।',
    'dashboard.orderOpportunitySimulator.toast.saveErrorTitle': 'सहेजने में त्रुटि',
    'dashboard.orderOpportunitySimulator.toast.saveErrorDescription': 'अनुकरण सहेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
    'dashboard.orderOpportunitySimulator.toast.notLoggedInError': 'अनुकरण/ऑर्डर सहेजने के लिए आपको लॉग इन होना चाहिए।',
    'dashboard.orderOpportunitySimulator.toast.noDataToSave': 'सहेजने के लिए कोई मान्य अनुकरण/ऑर्डर डेटा नहीं है।',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessTitle': 'ऑर्डर सहेजा गया',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessDescription': 'विशिष्ट ऑर्डर सफलतापूर्वक सहेजा गया है।',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorTitle': 'ऑर्डर सहेजने में त्रुटि',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorDescription': 'विशिष्ट ऑर्डर सहेजा नहीं जा सका। कृपया पुनः प्रयास करें।',

    'dashboard.api.binance.fetchError': 'बायनेंस से कीमतें प्राप्त करने में विफल: {status}',
    'dashboard.api.binance.errorTitle': 'कीमत प्राप्त करने में त्रुटि (बायनेंस)',
    'dashboard.api.binance.unknownError': 'बायनेंस से लाइव कीमतें प्राप्त नहीं की जा सकीं।',

    'dashboard.ai.errorTitle': 'AI विश्लेषण त्रुटि',
    'dashboard.ai.errorDescription': 'AI रुझान अपडेट नहीं किए जा सके।',
    'dashboard.ai.clientErrorReason': '{symbol} के लिए रुझान प्राप्त करने में क्लाइंट त्रुटि: {details}',
    'dashboard.ai.temporarilyDisabled': 'AI ट्रेंड विश्लेषण अस्थायी रूप से अक्षम है।',
    'dashboard.websocket.errorTitle': 'वेबसॉकेट त्रुटि',
    'dashboard.websocket.errorDescriptionBinance': 'बायनेंस लाइव मूल्य फ़ीड से कनेक्शन विफल। आवधिक अपडेट पर वापस जा रहे हैं।',
    'dashboard.websocket.errorDescriptionBinanceFallback': 'बायनेंस वेबसॉकेट विफल। REST फ़ॉलबैक का उपयोग किया जा रहा है।',
    'dashboard.websocket.errorMessage': 'त्रुटि संदेश: {message}, प्रकार: {type}',
    'dashboard.websocket.eventType': 'घटना प्रकार: {type}',

    'history.page.title': "ऑर्डर इतिहास",
    'history.menuItem': 'ऑर्डर इतिहास',
    'history.filters.dateRange': "दिनांक सीमा",
    'history.filters.startDate': "प्रारंभ तिथि",
    'history.filters.endDate': "अंतिम तिथि",
    'history.filters.pickDate': "एक तिथि चुनें",
    'history.filters.searchCrypto': "क्रिप्टो द्वारा खोजें",
    'history.filters.searchPlaceholder': "क्रिप्टो प्रतीक दर्ज करें (जैसे, BTC)",
    'history.filters.resetButton': "फ़िल्टर रीसेट करें",
    'history.export.csvButton': "CSV में निर्यात करें",
    'history.export.pdfButton': "PDF में निर्यात करें (प्रिंट)",
    'history.table.loading': "ऑर्डर इतिहास लोड हो रहा है...",
    'history.table.loadingError': "ऑर्डर इतिहास लोड करने में विफल।",
    'history.table.noOrders': "कोई ऑर्डर नहीं मिला।",
    'history.table.header.timestamp': 'दिनांक/समय',
    'history.table.header.originalPair': 'जोड़ी',
    'history.table.header.targetCrypto': 'लक्ष्य क्रिप्टो',
    'history.table.header.quoteCurrency': 'उद्धरण',
    'history.table.header.buyAmount': 'खरीदी गई राशि',
    'history.table.header.buyPrice': 'खरीद मूल्य',
    'history.table.header.buyComm': 'खरीद कमीशन',
    'history.table.header.sellPrice': 'बिक्री मूल्य',
    'history.table.header.sellComm': 'बिक्री कमीशन',
    'history.table.header.netProfit': 'शुद्ध लाभ',
    'history.toast.loadErrorTitle': 'त्रुटि',
    'history.toast.loadErrorDescription': 'ऑर्डर इतिहास लोड नहीं किया जा सका।',
    'history.toast.noDataExportTitle': 'कोई डेटा नहीं',
    'history.toast.noDataExportDescription': 'निर्यात करने के लिए कोई डेटा नहीं है।',
    'history.toast.csvExportSuccessTitle': 'निर्यात सफल',
    'history.toast.csvExportSuccessDescription': 'ऑर्डर इतिहास CSV में निर्यात किया गया।',

    'balance.page.title': "बैलेंस अवलोकन",
    'balance.page.loading': 'बैलेंस जानकारी लोड हो रही है...',
    'balance.menuItem': "बैलेंस",
    'balance.orderProfit.title': 'ऑर्डर लाभ/हानि विश्लेषण',
    'balance.orderProfit.chart.title': 'समय के साथ शुद्ध लाभ (ऑर्डर से)',

    'alertModal.title.edit': '{symbol} के लिए चेतावनी संपादित करें',
    'alertModal.title.create': '{symbol} के लिए चेतावनी सेट करें',
    'alertModal.description': 'वर्तमान मूल्य: ${price}',
    'alertModal.description.instruction': 'जब मूल्य आपके लक्ष्य से ऊपर या नीचे जाए तो सूचित हों।',
    'alertModal.form.targetPriceLabel': 'लक्ष्य मूल्य (USDT)',
    'alertModal.form.targetPricePlaceholder': 'जैसे, 50000',
    'alertModal.form.directionLabel': 'मुझे सूचित करें जब मूल्य हो',
    'alertModal.form.directionPlaceholder': 'दिशा चुनें',
    'alertModal.form.direction.above': 'ऊपर',
    'alertModal.form.direction.below': 'नीचे',
    'alertModal.button.save': 'चेतावनी सेट करें',
    'alertModal.button.update': 'चेतावनी अपडेट करें',
    'alertModal.button.delete': 'चेतावनी हटाएं',
    'alertModal.button.cancel': 'रद्द करें',
    'alertModal.toast.savedTitle': 'चेतावनी सहेजी गई',
    'alertModal.toast.savedDescription': '{symbol} के लिए आपकी मूल्य चेतावनी सेट कर दी गई है।',
    'alertModal.toast.updatedTitle': 'चेतावनी अपडेट की गई',
    'alertModal.toast.updatedDescription': '{symbol} के लिए आपकी मूल्य चेतावनी अपडेट कर दी गई है।',
    'alertModal.toast.deletedTitle': 'चेतावनी हटाई गई',
    'alertModal.toast.deletedDescription': '{symbol} के लिए मूल्य चेतावनी हटा दी गई है।',
    'alertModal.toast.errorTitle': 'चेतावनी सहेजने में त्रुटि',
    'alertModal.toast.errorDescriptionGeneric': 'चेतावनी सहेजी नहीं जा सकी।',
    'alertModal.toast.errorDeleteTitle': 'चेतावनी हटाने में त्रुटि',
    'alertModal.toast.errorDescriptionGenericDelete': 'चेतावनी हटाई नहीं जा सकी।',

    'activeAlerts.title': 'मेरी मूल्य चेतावनियां',
    'activeAlerts.description': 'अपनी सक्रिय और निष्क्रिय मूल्य चेतावनियों का प्रबंधन करें।',
    'activeAlerts.loading': 'चेतावनियां लोड हो रही हैं...',
    'activeAlerts.noAlerts': 'आपने अभी तक कोई मूल्य चेतावनी सेट नहीं की है।',
    'activeAlerts.refreshButton': 'चेतावनियां रीफ़्रेश करें',
    'activeAlerts.confirmDelete': 'क्या आप वाकई {symbol} के लिए इस चेतावनी को हटाना चाहते हैं?',
    'activeAlerts.table.symbol': 'क्रिप्टो',
    'activeAlerts.table.condition': 'शर्त',
    'activeAlerts.table.status': 'स्थिति',
    'activeAlerts.table.createdAt': 'निर्मित',
    'activeAlerts.table.actions': 'कार्रवाई',
    'activeAlerts.table.directionAbove': '> ',
    'activeAlerts.table.directionBelow': '< ',
    'activeAlerts.table.statusActive': 'सक्रिय',
    'activeAlerts.table.statusInactive': 'निष्क्रिय',
    'activeAlerts.table.activateSwitch': 'चेतावनी सक्रिय करें',
    'activeAlerts.table.deactivateSwitch': 'चेतावनी निष्क्रिय करें',
    'activeAlerts.button.edit': 'चेतावनी संपादित करें',
    'activeAlerts.button.delete': 'चेतावनी हटाएं',
    'activeAlerts.toast.fetchErrorTitle': 'त्रुटि',
    'activeAlerts.toast.fetchErrorDescription': 'आपकी मूल्य चेतावनियां लोड नहीं की जा सकीं।',
    'activeAlerts.toast.deletedTitle': 'चेतावनी हटाई गई',
    'activeAlerts.toast.deletedDescription': '{symbol} के लिए चेतावनी हटा दी गई है।',
    'activeAlerts.toast.deleteErrorTitle': 'हटाने में त्रुटि',
    'activeAlerts.toast.deleteErrorDescription': 'चेतावनी हटाई नहीं जा सकी।',
    'activeAlerts.toast.activatedTitle': 'चेतावनी सक्रिय',
    'activeAlerts.toast.activatedDescription': '{symbol} के लिए चेतावनी अब सक्रिय है।',
    'activeAlerts.toast.deactivatedTitle': 'चेतावनी निष्क्रिय',
    'activeAlerts.toast.deactivatedDescription': '{symbol} के लिए चेतावनी अब निष्क्रिय है।',
    'activeAlerts.toast.toggleErrorTitle': 'चेतावनी अपडेट करने में त्रुटि',
    'activeAlerts.toast.toggleErrorDescription': 'चेतावनी स्थिति अपडेट नहीं की जा सकी।',

    'zod.email.invalid': 'अमान्य ईमेल पता।',
    'zod.password.required': 'पासवर्ड आवश्यक है।',
    'zod.password.minLength': 'पासवर्ड में कम से कम 8 वर्ण होने चाहिए।',
    'zod.password.lowercase': 'पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए।',
    'zod.password.uppercase': 'पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए।',
    'zod.password.number': 'पासवर्ड में कम से कम एक संख्या होनी चाहिए।',
    'zod.password.specialChar': 'पासवर्ड में कम से कम एक विशेष वर्ण होना चाहिए।',
    'zod.password.confirmMatch': 'पासवर्ड मेल नहीं खाते।',
    'zod.password.currentRequired': 'वर्तमान पासवर्ड आवश्यक है।',
    'zod.password.newMinLength': 'नए पासवर्ड में कम से कम 8 वर्ण होने चाहिए।',
    'zod.password.newLowercase': 'नए पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए।',
    'zod.password.newUppercase': 'नए पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए।',
    'zod.password.newNumber': 'नए पासवर्ड में कम से कम एक संख्या होनी चाहिए।',
    'zod.password.newSpecialChar': 'नए पासवर्ड में कम से कम एक विशेष वर्ण होना चाहिए।',
    'zod.password.newConfirmMatch': 'नए पासवर्ड मेल नहीं खाते।',
    'zod.orderOpportunity.selectPair': 'कृपया एक ट्रेडिंग जोड़ी चुनें।',
    'zod.orderOpportunity.positiveInputAmount': 'राशि एक सकारात्मक संख्या होनी चाहिए।',
    'zod.orderOpportunity.marketPricePositive': 'बाजार मूल्य एक सकारात्मक संख्या होनी चाहिए।',
    'zod.orderOpportunity.purchasePriceUsdtPositive': 'यूएसडीटी में खरीद मूल्य एक सकारात्मक संख्या होनी चाहिए।',
    'zod.orderOpportunity.targetPricePositive': 'लक्ष्य मूल्य एक सकारात्मक संख्या होनी चाहिए。',
    'zod.alert.targetPricePositive': 'लक्ष्य मूल्य एक धनात्मक संख्या होनी चाहिए।',
    'zod.alert.directionRequired': 'कृपया चेतावनी के लिए एक दिशा चुनें।',
    'footer.createdBy': 'IA द्वारा एलन सोटो द्वारा बनाया गया',
  },
  zh: { 
    'app.name': 'SimulTradex',
    'app.loadingMessage': '正在加载SimulTradex...',
    'settings.title': '设置',
    'settings.myAccount': '我的账户',
    'settings.accountSettings': '账户设置',
    'settings.language': '语言',
    'settings.logout': '登出',
    'header.userMenu.title': '用户菜单',
    'dashboard.title': '仪表板',
    'dashboard.marketOverview': '市场概览',
    'dashboard.loadingPrices': '正在加载实时价格...',
    'dashboard.portfolioBalance': '投资组合余额',
    'dashboard.portfolioBalance.publicSourceMessage': "正在显示来自公共来源的市场数据。",
    'dashboard.connectionStatus.title': '连接问题',
    'dashboard.connectionStatus.noFeed': '目前未收到实时价格更新。正在尝试连接...',
    'dashboard.connectionStatus.fallbackTitle': '正在使用备用连接',
    'dashboard.connectionStatus.restFallbackActive': 'WebSocket连接失败。正在使用定期的REST API更新价格。',
    'dashboard.cryptoCard.alertButton.title': '设置价格提醒',
    'dashboard.cryptoCard.alertButton.label': '设置提醒',
    'dashboard.alerts.fetchErrorTitle': '提醒错误',
    'dashboard.alerts.fetchErrorDescription': '无法加载您的活动价格提醒。',
    'dashboard.alerts.triggeredTitle': '价格提醒已触发！',
    'dashboard.alerts.triggeredDescription': '{symbol} 已达到您的目标价格 ${targetPrice}。当前价格：${currentPrice}。',
    'dashboard.ai.historicalDataError': '无法获取 {symbol} 的历史数据。',

    'login.title': '登录',
    'login.description': '登录您的帐户',
    'login.emailLabel': '电子邮件',
    'login.emailPlaceholder': 'ni@example.com',
    'login.passwordLabel': '密码',
    'login.submitButton': '登录',
    'login.signupPrompt': '还没有账户？',
    'login.signupLink': '注册',
    'login.error.invalidCredentials': '无效的电子邮件或密码。',
    'login.error.unknown': '发生未知错误。',
    'login.error.passwordTooWeak': '密码不符合安全要求。必须包含8个以上字符，包括大写字母、小写字母、数字和符号。',
    'login.required': '请登录以查看此信息。',

    'signup.title': '注册',
    'signup.description': '创建您的账户',
    'signup.emailLabel': '电子邮件',
    'signup.emailPlaceholder': 'ni@example.com',
    'signup.passwordLabel': '密码',
    'signup.confirmPasswordLabel': '确认密码',
    'signup.submitButton': '注册',
    'signup.loginPrompt': '已经有账户了？',
    'signup.loginLink': '登录',
    'signup.error.emailTaken': '此电子邮件已被注册。',
    'signup.error.unknown': '发生未知错误。',
    'signup.error.passwordTooWeak': '密码不符合安全要求。必须包含8个以上字符，包括大写字母、小写字母、数字和符号。',
    
    'account.passwordChange.title': "更改密码",
    'account.passwordChange.description': "更新您的帐户密码。",
    'account.passwordChange.currentPasswordLabel': "当前密码",
    'account.passwordChange.newPasswordLabel': "新密码",
    'account.passwordChange.confirmNewPasswordLabel': "确认新密码",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "更改密码",
    'account.passwordChange.toast.changedTitle': "密码已更改",
    'account.passwordChange.toast.changedDescription': "您的密码已成功更新。",
    'account.passwordChange.toast.failedTitle': "密码更改失败",
    'account.passwordChange.toast.failedDescriptionIncorrect': "当前密码不正确。",
    'account.passwordChange.toast.failedDescriptionWeak': '新密码不符合安全要求。',

    'account.page.title': "账户设置",
    'account.page.userInfoTitle': "用户信息",
    'account.page.emailLabel': "电子邮件：",

    'dashboard.cryptoCard.tooltip.reason': "原因：",
    'dashboard.cryptoCard.tooltip.confidence': "置信度：",
    'dashboard.cryptoCard.trend.upward': "上涨趋势",
    'dashboard.cryptoCard.trend.downward': "下跌趋势",
    'dashboard.cryptoCard.trend.sideways': "横盘趋势",
    'dashboard.cryptoCard.trend.notAvailable': "趋势不可用",

    'dashboard.orderOpportunitySimulator.title': '订单与机会模拟器',
    'dashboard.orderOpportunitySimulator.description': '模拟交易并查看增量利润百分比下的潜在卖出机会。',
    'dashboard.orderOpportunitySimulator.operationPairLabel': '交易对',
    'dashboard.orderOpportunitySimulator.inputAmountLabel': '数量 ({currency})',
    'dashboard.orderOpportunitySimulator.purchasePriceUsdtLabel': '{targetCrypto}的购买价格 (USDT)',
    'dashboard.orderOpportunitySimulator.marketPairPriceLabel': '市场价格 ({pair})',
    'dashboard.orderOpportunitySimulator.inputDivPurchasePriceLabel': '输入数量 / 购买价格',
    'dashboard.orderOpportunitySimulator.marketPriceDisplayLabel': '市场价格 ({cur2}/{cur1})',
    'dashboard.orderOpportunitySimulator.selectPairPlaceholder': '选择交易对',
    'dashboard.orderOpportunitySimulator.table.header.operation': '操作',
    'dashboard.orderOpportunitySimulator.table.header.amountCur1Display': '数量 ({currency1})',
    'dashboard.orderOpportunitySimulator.table.header.marketPriceDisplay': '市场价格',
    'dashboard.orderOpportunitySimulator.table.header.amountCur2Display': '数量 ({currency2})',
    'dashboard.orderOpportunitySimulator.table.header.commissionDisplay': '手续费 ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.netProfitDisplay': '净利润 ({currency})',
    'dashboard.orderOpportunitySimulator.table.header.actions': '操作',
    'dashboard.orderOpportunitySimulator.exchangeOperation': '用{cur1}兑换{cur2}',
    'dashboard.orderOpportunitySimulator.sellOperationPerc': '卖出{targetCrypto} (+{perc}%)',
    'dashboard.orderOpportunitySimulator.priceUnavailable': '价格不可用',
    'dashboard.orderOpportunitySimulator.priceUnavailableShort': '不可用',
    'dashboard.orderOpportunitySimulator.invalidMarketPrice': '无效的市场价格',
    'dashboard.orderOpportunitySimulator.invalidPurchasePrice': '无效的购买价格',
    'dashboard.orderOpportunitySimulator.calculating': '计算中...',
    'dashboard.orderOpportunitySimulator.enterValuesPrompt': '请选择一个交易对并输入数量以查看模拟。',
    'dashboard.orderOpportunitySimulator.enterValuesPromptFull': '请选择交易对，输入数量和购买价格以查看模拟。',
    'dashboard.orderOpportunitySimulator.commissionInfo': '手续费为{quote_currency}交易额的{rate}%。',
    'dashboard.orderOpportunitySimulator.saveButton': '保存完整模拟',
    'dashboard.orderOpportunitySimulator.saveOrderButton': '保存订单',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessTitle': '模拟已保存',
    'dashboard.orderOpportunitySimulator.toast.savedSuccessDescription': '您的模拟已成功保存。',
    'dashboard.orderOpportunitySimulator.toast.saveErrorTitle': '保存错误',
    'dashboard.orderOpportunitySimulator.toast.saveErrorDescription': '无法保存模拟。请重试。',
    'dashboard.orderOpportunitySimulator.toast.notLoggedInError': '您必须登录才能保存模拟/订单。',
    'dashboard.orderOpportunitySimulator.toast.noDataToSave': '没有有效的模拟/订单数据可保存。',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessTitle': '订单已保存',
    'dashboard.orderOpportunitySimulator.toast.orderSavedSuccessDescription': '特定订单已成功保存。',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorTitle': '订单保存错误',
    'dashboard.orderOpportunitySimulator.toast.orderSaveErrorDescription': '无法保存特定订单。请重试。',

    'dashboard.api.binance.fetchError': '从币安获取价格失败：{status}',
    'dashboard.api.binance.errorTitle': '价格获取错误 (币安)',
    'dashboard.api.binance.unknownError': '无法从币安获取实时价格。',

    'dashboard.ai.errorTitle': 'AI分析错误',
    'dashboard.ai.errorDescription': '无法更新AI趋势。',
    'dashboard.ai.clientErrorReason': '客户端获取{symbol}趋势时出错：{details}',
    'dashboard.ai.temporarilyDisabled': 'AI趋势分析暂时禁用。',
    'dashboard.websocket.errorTitle': 'WebSocket错误',
    'dashboard.websocket.errorDescriptionBinance': '连接币安实时价格源失败。将回退到定期更新。',
    'dashboard.websocket.errorDescriptionBinanceFallback': '币安WebSocket失败。正在使用REST备用方案。',
    'dashboard.websocket.errorMessage': '错误信息：{message}，类型：{type}',
    'dashboard.websocket.eventType': '事件类型：{type}',

    'history.page.title': "订单历史",
    'history.menuItem': '订单历史',
    'history.filters.dateRange': "日期范围",
    'history.filters.startDate': "开始日期",
    'history.filters.endDate': "结束日期",
    'history.filters.pickDate': "选择日期",
    'history.filters.searchCrypto': "按加密货币搜索",
    'history.filters.searchPlaceholder': "输入加密货币代码 (例如 BTC)",
    'history.filters.resetButton': "重置筛选器",
    'history.export.csvButton': "导出为CSV",
    'history.export.pdfButton': "导出为PDF (打印)",
    'history.table.loading': "正在加载订单历史...",
    'history.table.loadingError': "加载订单历史失败。",
    'history.table.noOrders': "未找到订单。",
    'history.table.header.timestamp': '日期/时间',
    'history.table.header.originalPair': '交易对',
    'history.table.header.targetCrypto': '目标加密货币',
    'history.table.header.quoteCurrency': '报价货币',
    'history.table.header.buyAmount': '购买数量',
    'history.table.header.buyPrice': '购买价格',
    'history.table.header.buyComm': '购买手续费',
    'history.table.header.sellPrice': '出售价格',
    'history.table.header.sellComm': '出售手续费',
    'history.table.header.netProfit': '净利润',
    'history.toast.loadErrorTitle': '错误',
    'history.toast.loadErrorDescription': '无法加载订单历史。',
    'history.toast.noDataExportTitle': '无数据',
    'history.toast.noDataExportDescription': '没有可导出的数据。',
    'history.toast.csvExportSuccessTitle': '导出成功',
    'history.toast.csvExportSuccessDescription': '订单历史已导出为CSV。',

    'balance.page.title': "余额概览",
    'balance.page.loading': '正在加载余额信息...',
    'balance.menuItem': "余额",
    'balance.orderProfit.title': '订单盈亏分析',
    'balance.orderProfit.chart.title': '净利润随时间变化（来自订单）',

    'alertModal.title.edit': '编辑{symbol}的提醒',
    'alertModal.title.create': '为{symbol}设置提醒',
    'alertModal.description': '当前价格：${price}',
    'alertModal.description.instruction': '当价格高于或低于您的目标时收到通知。',
    'alertModal.form.targetPriceLabel': '目标价格 (USDT)',
    'alertModal.form.targetPricePlaceholder': '例如, 50000',
    'alertModal.form.directionLabel': '当价格为以下情况时通知我',
    'alertModal.form.directionPlaceholder': '选择方向',
    'alertModal.form.direction.above': '高于',
    'alertModal.form.direction.below': '低于',
    'alertModal.button.save': '设置提醒',
    'alertModal.button.update': '更新提醒',
    'alertModal.button.delete': '删除提醒',
    'alertModal.button.cancel': '取消',
    'alertModal.toast.savedTitle': '提醒已保存',
    'alertModal.toast.savedDescription': '{symbol}的价格提醒已设置。',
    'alertModal.toast.updatedTitle': '提醒已更新',
    'alertModal.toast.updatedDescription': '{symbol}的价格提醒已更新。',
    'alertModal.toast.deletedTitle': '提醒已删除',
    'alertModal.toast.deletedDescription': '{symbol}的价格提醒已删除。',
    'alertModal.toast.errorTitle': '保存提醒时出错',
    'alertModal.toast.errorDescriptionGeneric': '无法保存提醒。',
    'alertModal.toast.errorDeleteTitle': '删除提醒时出错',
    'alertModal.toast.errorDescriptionGenericDelete': '无法删除提醒。',

    'activeAlerts.title': '我的价格提醒',
    'activeAlerts.description': '管理您的活动和非活动价格提醒。',
    'activeAlerts.loading': '正在加载提醒...',
    'activeAlerts.noAlerts': '您尚未设置任何价格提醒。',
    'activeAlerts.refreshButton': '刷新提醒',
    'activeAlerts.confirmDelete': '您确定要删除{symbol}的此提醒吗？',
    'activeAlerts.table.symbol': '加密货币',
    'activeAlerts.table.condition': '条件',
    'activeAlerts.table.status': '状态',
    'activeAlerts.table.createdAt': '创建于',
    'activeAlerts.table.actions': '操作',
    'activeAlerts.table.directionAbove': '> ',
    'activeAlerts.table.directionBelow': '< ',
    'activeAlerts.table.statusActive': '活动',
    'activeAlerts.table.statusInactive': '非活动',
    'activeAlerts.table.activateSwitch': '激活提醒',
    'activeAlerts.table.deactivateSwitch': '停用提醒',
    'activeAlerts.button.edit': '编辑提醒',
    'activeAlerts.button.delete': '删除提醒',
    'activeAlerts.toast.fetchErrorTitle': '错误',
    'activeAlerts.toast.fetchErrorDescription': '无法加载您的价格提醒。',
    'activeAlerts.toast.deletedTitle': '提醒已删除',
    'activeAlerts.toast.deletedDescription': '{symbol}的提醒已删除。',
    'activeAlerts.toast.deleteErrorTitle': '删除错误',
    'activeAlerts.toast.deleteErrorDescription': '无法删除提醒。',
    'activeAlerts.toast.activatedTitle': '提醒已激活',
    'activeAlerts.toast.activatedDescription': '{symbol}的提醒现已激活。',
    'activeAlerts.toast.deactivatedTitle': '提醒已停用',
    'activeAlerts.toast.deactivatedDescription': '{symbol}的提醒现已停用。',
    'activeAlerts.toast.toggleErrorTitle': '更新提醒时出错',
    'activeAlerts.toast.toggleErrorDescription': '无法更新提醒状态。',


    'zod.email.invalid': '无效的电子邮件地址。',
    'zod.password.required': '密码是必需的。',
    'zod.password.minLength': '密码必须至少包含8个字符。',
    'zod.password.lowercase': '密码必须包含至少一个小写字母。',
    'zod.password.uppercase': '密码必须包含至少一个大写字母。',
    'zod.password.number': '密码必须包含至少一个数字。',
    'zod.password.specialChar': '密码必须包含至少一个特殊字符。',
    'zod.password.confirmMatch': '密码不匹配。',
    'zod.password.currentRequired': '当前密码是必需的。',
    'zod.password.newMinLength': '新密码必须至少包含8个字符。',
    'zod.password.newLowercase': '新密码必须包含至少一个小写字母。',
    'zod.password.newUppercase': '新密码必须包含至少一个大写字母。',
    'zod.password.newNumber': '新密码必须包含至少一个数字。',
    'zod.password.newSpecialChar': '新密码必须包含至少一个特殊字符。',
    'zod.password.newConfirmMatch': '新密码不匹配。',
    'zod.orderOpportunity.selectPair': '请选择一个交易对。',
    'zod.orderOpportunity.positiveInputAmount': '金额必须是正数。',
    'zod.orderOpportunity.marketPricePositive': '市场价格必须是正数。',
    'zod.orderOpportunity.purchasePriceUsdtPositive': 'USDT购买价格必须是正数。',
    'zod.orderOpportunity.targetPricePositive': '目标价格必须是正数。',
    'zod.alert.targetPricePositive': '目标价格必须是正数。',
    'zod.alert.directionRequired': '请选择提醒的方向。',
    'footer.createdBy': '由 Allan Soto 使用 AI 创建',
  }
};

const DEFAULT_LANGUAGE: LanguageCode = 'en';

export const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setCurrentLanguage] = useState<LanguageCode>(DEFAULT_LANGUAGE);
  const [translations, setTranslations] = useState<Record<string, string>>(
    translationsData[DEFAULT_LANGUAGE]
  );
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const storedLanguage = typeof window !== 'undefined' ? localStorage.getItem('simultradex_language') as LanguageCode | null : null;
    if (storedLanguage && translationsData[storedLanguage]) {
      setCurrentLanguage(storedLanguage);
      setTranslations(translationsData[storedLanguage]);
    } else {
      if (typeof window !== 'undefined' && storedLanguage !== DEFAULT_LANGUAGE) {
         localStorage.setItem('simultradex_language', DEFAULT_LANGUAGE);
      }
    }
    setHydrated(true); 
  }, []);

  const setLanguage = useCallback((langCode: LanguageCode) => {
    if (translationsData[langCode]) {
      setCurrentLanguage(langCode);
      setTranslations(translationsData[langCode]);
      if (typeof window !== 'undefined') {
        localStorage.setItem('simultradex_language', langCode);
      }
    } else {
      console.warn(`Language code ${langCode} not found in translations. Falling back to default.`);
      setCurrentLanguage(DEFAULT_LANGUAGE);
      setTranslations(translationsData[DEFAULT_LANGUAGE]);
      if (typeof window !== 'undefined') {
        localStorage.setItem('simultradex_language', DEFAULT_LANGUAGE);
      }
    }
  }, []);

  useEffect(() => {
    if (hydrated && typeof window !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language, hydrated]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations, hydrated }}>
      {children}
    </LanguageContext.Provider>
  );
};
