
'use client';

import type { ReactNode } from 'react';
import { createContext, useState, useEffect, useCallback } from 'react';
import { LANGUAGES } from '@/lib/constants';

export type LanguageCode = typeof LANGUAGES[number]['code'];

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  translations: Record<string, string>;
}

// Define basic translations
// NOTE: New keys have been added with English translations.
// For other languages (es, fr, hi, zh), these new keys will need to be translated and added.
const translationsData: Record<LanguageCode, Record<string, string>> = {
  en: {
    'app.name': 'SimulTradex',
    'app.loadingMessage': 'Loading SimulTradex...',
    'settings.myAccount': 'My Account',
    'settings.accountSettings': 'Account Settings',
    'settings.language': 'Language',
    'settings.logout': 'Log out',
    'dashboard.title': 'Dashboard',
    'dashboard.marketOverview': 'Market Overview',
    'dashboard.orderSimulator': 'Order Simulator',
    'dashboard.opportunitySimulator': 'Opportunity Simulator',
    'login.title': 'Log In',
    'login.description': 'Log in to your account',
    'login.emailLabel': 'Email',
    'login.emailPlaceholder': 'you@example.com',
    'login.passwordLabel': 'Password',
    'login.submitButton': 'Log In',
    'login.signupPrompt': "Don't have an account?",
    'login.signupLink': 'Sign up',
    'login.error.invalidCredentials': 'Invalid email or password.',
    'signup.title': 'Sign Up',
    'signup.description': 'Create your account',
    'signup.emailLabel': 'Email',
    'signup.emailPlaceholder': 'you@example.com',
    'signup.passwordLabel': 'Password',
    'signup.confirmPasswordLabel': 'Confirm Password',
    'signup.submitButton': 'Sign Up',
    'signup.loginPrompt': 'Already have an account?',
    'signup.loginLink': 'Log in',
    'signup.error.unknown': 'An unknown error occurred.',

    'account.apiKey.title': "Binance API Connection",
    'account.apiKey.description': "Connect your Binance account to fetch real-time data. Your keys are stored locally (mock).",
    'account.apiKey.connectedStatus': "Connected to Binance API.",
    'account.apiKey.disconnectButton': "Disconnect",
    'account.apiKey.apiKeyLabel': "API Key",
    'account.apiKey.apiKeyPlaceholder': "Your Binance API Key",
    'account.apiKey.apiSecretLabel': "API Secret",
    'account.apiKey.apiSecretPlaceholder': "Your Binance API Secret",
    'account.apiKey.connectButton': "Connect to Binance",
    'account.apiKey.error.connectionFailed': "Connection failed: Invalid API Key or Secret.",
    'account.apiKey.toast.connectionFailedTitle': "API Connection Failed",
    'account.apiKey.toast.connectionFailedDescription': "Invalid API Key or Secret.",
    'account.apiKey.toast.connectedTitle': "API Connected",
    'account.apiKey.toast.connectedDescription': "Successfully connected to Binance API.",

    'account.passwordChange.title': "Change Password",
    'account.passwordChange.description': "Update your account password.",
    'account.passwordChange.currentPasswordLabel': "Current Password",
    'account.passwordChange.newPasswordLabel': "New Password",
    'account.passwordChange.confirmNewPasswordLabel': "Confirm New Password",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "Change Password",
    'account.passwordChange.toast.changedTitle': "Password Changed",
    'account.passwordChange.toast.changedDescription': "Your password has been successfully updated.",
    'account.passwordChange.toast.failedTitle': "Password Change Failed",
    'account.passwordChange.toast.failedDescriptionIncorrect': "Incorrect current password.",

    'account.page.title': "Account Settings",
    'account.page.userInfoTitle': "User Information",
    'account.page.emailLabel': "Email:",

    'dashboard.cryptoCard.tooltip.reason': "Reason:",
    'dashboard.cryptoCard.tooltip.confidence': "Confidence:",
    'dashboard.cryptoCard.trend.upward': "Upward trend",
    'dashboard.cryptoCard.trend.downward': "Downward trend",
    'dashboard.cryptoCard.trend.sideways': "Sideways trend",
    'dashboard.cryptoCard.trend.notAvailable': "Trend N/A",

    'dashboard.opportunityList.title': "Opportunity Simulator",
    'dashboard.opportunityList.description': "Potential trade opportunities based on current prices and target profit percentages.",
    'dashboard.opportunityList.table.header.crypto': "Crypto",
    'dashboard.opportunityList.table.header.currentPrice': "Current Price",
    'dashboard.opportunityList.table.header.targetSell': "Target Sell (+Profit)",
    'dashboard.opportunityList.table.header.potentialGain': "Potential Gain",
    'dashboard.opportunityList.emptyMessage': "No opportunities to display currently, or prices are still loading.",

    'dashboard.orderSimulator.title': "Order Simulator",
    'dashboard.orderSimulator.description': "Simulate a buy and sell order to estimate potential profit or loss. Input quantity, buy price, and sell price. Current market prices are pre-filled for buy price.",
    'dashboard.orderSimulator.cryptoLabel': "Cryptocurrency",
    'dashboard.orderSimulator.selectPlaceholder': "Select a crypto",
    'dashboard.orderSimulator.tradingPairDesc': "Trading Pair: {symbol}/{quoteCurrency}",
    'dashboard.orderSimulator.quantityLabel': "Quantity ({symbol})",
    'dashboard.orderSimulator.quantityLabelNoSymbol': "Quantity",
    'dashboard.orderSimulator.buyPriceLabel': "Buy Price ({quoteCurrency} per unit)",
    'dashboard.orderSimulator.sellPriceLabel': "Sell Price ({quoteCurrency} per unit)",
    'dashboard.orderSimulator.commissionDesc': "A commission of {rate}% will be applied to both buy and sell transactions.",
    'dashboard.orderSimulator.submitButton': "Simulate Trade",
    'dashboard.orderSimulator.toast.errorTitle': "Simulation Error",
    'dashboard.orderSimulator.toast.errorSellPrice': "Sell price must be greater than buy price.",
    'dashboard.orderSimulator.toast.completeTitle': "Simulation Complete",
    'dashboard.orderSimulator.toast.completeDescription': "Simulated trade for {quantity} {symbol} processed.",
    'dashboard.orderSimulator.result.title': "Simulation Result for {quantity} {symbol}",
    'dashboard.orderSimulator.result.grossProfit': "Gross Profit:",
    'dashboard.orderSimulator.result.totalCommission': "Total Commission:",
    'dashboard.orderSimulator.result.netProfitLoss': "Net Profit / Loss:",
    
    'dashboard.websocket.connectedTitle': 'Real-time Feed Connected',
    'dashboard.websocket.connectedDescription': 'Live prices from Binance are now active.',
    'dashboard.websocket.errorTitle': 'Real-time Feed Error',
    'dashboard.websocket.errorDescription': 'There was an issue with the live price feed. Attempting to reconnect.',
    'dashboard.websocket.disconnectedTitle': 'Real-time Feed Disconnected',
    'dashboard.websocket.reconnectingDescription': 'Attempting to reconnect to live prices... Attempt {attempt}/{maxAttempts}',
    'dashboard.websocket.failedConnectionTitle': 'Real-time Feed Failed',
    'dashboard.websocket.failedConnectionDescription': 'Could not establish connection to live prices after multiple attempts. Please check your internet connection or try again later.',
    
    'zod.email.invalid': 'Invalid email address.',
    'zod.password.required': 'Password is required.',
    'zod.password.minLength': 'Password must be at least 8 characters.',
    'zod.password.lowercase': 'Password must contain at least one lowercase letter.',
    'zod.password.uppercase': 'Password must contain at least one uppercase letter.',
    'zod.password.number': 'Password must contain at least one number.',
    'zod.password.specialChar': 'Password must contain at least one special character.',
    'zod.password.confirmMatch': "Passwords don't match.",
    'zod.apiKey.short': 'API Key seems too short.',
    'zod.apiSecret.short': 'API Secret seems too short.',
    'zod.password.currentRequired': 'Current password is required.',
    'zod.password.newMinLength': 'Password must be at least 8 characters.', // same as zod.password.minLength but contextually different
    'zod.password.newLowercase': 'Password must contain at least one lowercase letter.', // same as zod.password.lowercase
    'zod.password.newUppercase': 'Password must contain at least one uppercase letter.', // same as zod.password.uppercase
    'zod.password.newNumber': 'Password must contain at least one number.', // same as zod.password.number
    'zod.password.newSpecialChar': 'Password must contain at least one special character.', // same as zod.password.specialChar
    'zod.password.newConfirmMatch': "New passwords don't match.", // same as zod.password.confirmMatch
    'zod.order.selectCrypto': 'Please select a cryptocurrency.',
    'zod.order.positiveNumber': 'Must be a positive number.',
  },
  es: {
    'app.name': 'SimulTradex',
    'app.loadingMessage': 'Cargando SimulTradex...',
    'settings.myAccount': 'Mi Cuenta',
    'settings.accountSettings': 'Configuración de Cuenta',
    'settings.language': 'Idioma',
    'settings.logout': 'Cerrar Sesión',
    'dashboard.title': 'Tablero',
    'dashboard.marketOverview': 'Resumen del Mercado',
    'dashboard.orderSimulator': 'Simulador de Órdenes',
    'dashboard.opportunitySimulator': 'Simulador de Oportunidades',
    'login.title': 'Iniciar Sesión',
    'login.description': 'Inicia sesión en tu cuenta',
    'login.emailLabel': 'Correo Electrónico',
    'login.emailPlaceholder': 'tu@ejemplo.com',
    'login.passwordLabel': 'Contraseña',
    'login.submitButton': 'Iniciar Sesión',
    'login.signupPrompt': '¿No tienes una cuenta?',
    'login.signupLink': 'Regístrate',
    'login.error.invalidCredentials': 'Correo electrónico o contraseña no válidos.',
    'signup.title': 'Crear Cuenta',
    'signup.description': 'Crea tu cuenta',
    'signup.emailLabel': 'Correo Electrónico',
    'signup.emailPlaceholder': 'tu@ejemplo.com',
    'signup.passwordLabel': 'Contraseña',
    'signup.confirmPasswordLabel': 'Confirmar Contraseña',
    'signup.submitButton': 'Crear Cuenta',
    'signup.loginPrompt': '¿Ya tienes una cuenta?',
    'signup.loginLink': 'Iniciar Sesión',
    'signup.error.unknown': 'Ocurrió un error desconocido.',

    'account.apiKey.title': "Conexión API de Binance",
    'account.apiKey.description': "Conecta tu cuenta de Binance para obtener datos en tiempo real. Tus claves se almacenan localmente (simulado).",
    'account.apiKey.connectedStatus': "Conectado a la API de Binance.",
    'account.apiKey.disconnectButton': "Desconectar",
    'account.apiKey.apiKeyLabel': "Clave API",
    'account.apiKey.apiKeyPlaceholder': "Tu clave API de Binance",
    'account.apiKey.apiSecretLabel': "Secreto API",
    'account.apiKey.apiSecretPlaceholder': "Tu secreto API de Binance",
    'account.apiKey.connectButton': "Conectar a Binance",
    'account.apiKey.error.connectionFailed': "Falló la conexión: Clave API o Secreto no válidos.",
    'account.apiKey.toast.connectionFailedTitle': "Falló la Conexión API",
    'account.apiKey.toast.connectionFailedDescription': "Clave API o Secreto no válidos.",
    'account.apiKey.toast.connectedTitle': "API Conectada",
    'account.apiKey.toast.connectedDescription': "Conectado exitosamente a la API de Binance.",

    'account.passwordChange.title': "Cambiar Contraseña",
    'account.passwordChange.description': "Actualiza la contraseña de tu cuenta.",
    'account.passwordChange.currentPasswordLabel': "Contraseña Actual",
    'account.passwordChange.newPasswordLabel': "Nueva Contraseña",
    'account.passwordChange.confirmNewPasswordLabel': "Confirmar Nueva Contraseña",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "Cambiar Contraseña",
    'account.passwordChange.toast.changedTitle': "Contraseña Cambiada",
    'account.passwordChange.toast.changedDescription': "Tu contraseña ha sido actualizada exitosamente.",
    'account.passwordChange.toast.failedTitle': "Falló el Cambio de Contraseña",
    'account.passwordChange.toast.failedDescriptionIncorrect': "Contraseña actual incorrecta.",

    'account.page.title': "Configuración de Cuenta",
    'account.page.userInfoTitle': "Información del Usuario",
    'account.page.emailLabel': "Correo Electrónico:",

    'dashboard.cryptoCard.tooltip.reason': "Razón:",
    'dashboard.cryptoCard.tooltip.confidence': "Confianza:",
    'dashboard.cryptoCard.trend.upward': "Tendencia alcista",
    'dashboard.cryptoCard.trend.downward': "Tendencia bajista",
    'dashboard.cryptoCard.trend.sideways': "Tendencia lateral",
    'dashboard.cryptoCard.trend.notAvailable': "Tendencia N/A",

    'dashboard.opportunityList.title': "Simulador de Oportunidades",
    'dashboard.opportunityList.description': "Oportunidades de trade potenciales basadas en precios actuales y porcentajes de ganancia objetivo.",
    'dashboard.opportunityList.table.header.crypto': "Cripto",
    'dashboard.opportunityList.table.header.currentPrice': "Precio Actual",
    'dashboard.opportunityList.table.header.targetSell': "Venta Objetivo (+Ganancia)",
    'dashboard.opportunityList.table.header.potentialGain': "Ganancia Potencial",
    'dashboard.opportunityList.emptyMessage': "No hay oportunidades para mostrar actualmente, o los precios aún se están cargando.",

    'dashboard.orderSimulator.title': "Simulador de Órdenes",
    'dashboard.orderSimulator.description': "Simula una orden de compra y venta para estimar la ganancia o pérdida potencial. Ingresa cantidad, precio de compra y precio de venta. Los precios de mercado actuales se rellenan automáticamente para el precio de compra.",
    'dashboard.orderSimulator.cryptoLabel': "Criptomoneda",
    'dashboard.orderSimulator.selectPlaceholder': "Selecciona una cripto",
    'dashboard.orderSimulator.tradingPairDesc': "Par de Trading: {symbol}/{quoteCurrency}",
    'dashboard.orderSimulator.quantityLabel': "Cantidad ({symbol})",
    'dashboard.orderSimulator.quantityLabelNoSymbol': "Cantidad",
    'dashboard.orderSimulator.buyPriceLabel': "Precio de Compra ({quoteCurrency} por unidad)",
    'dashboard.orderSimulator.sellPriceLabel': "Precio de Venta ({quoteCurrency} por unidad)",
    'dashboard.orderSimulator.commissionDesc': "Se aplicará una comisión del {rate}% a las transacciones de compra y venta.",
    'dashboard.orderSimulator.submitButton': "Simular Trade",
    'dashboard.orderSimulator.toast.errorTitle': "Error de Simulación",
    'dashboard.orderSimulator.toast.errorSellPrice': "El precio de venta debe ser mayor que el precio de compra.",
    'dashboard.orderSimulator.toast.completeTitle': "Simulación Completada",
    'dashboard.orderSimulator.toast.completeDescription': "Trade simulado para {quantity} {symbol} procesado.",
    'dashboard.orderSimulator.result.title': "Resultado de Simulación para {quantity} {symbol}",
    'dashboard.orderSimulator.result.grossProfit': "Ganancia Bruta:",
    'dashboard.orderSimulator.result.totalCommission': "Comisión Total:",
    'dashboard.orderSimulator.result.netProfitLoss': "Ganancia / Pérdida Neta:",

    'dashboard.websocket.connectedTitle': 'Fuente en Tiempo Real Conectada',
    'dashboard.websocket.connectedDescription': 'Los precios en vivo de Binance ahora están activos.',
    'dashboard.websocket.errorTitle': 'Error en Fuente en Tiempo Real',
    'dashboard.websocket.errorDescription': 'Hubo un problema con la fuente de precios en vivo. Intentando reconectar.',
    'dashboard.websocket.disconnectedTitle': 'Fuente en Tiempo Real Desconectada',
    'dashboard.websocket.reconnectingDescription': 'Intentando reconectar a los precios en vivo... Intento {attempt}/{maxAttempts}',
    'dashboard.websocket.failedConnectionTitle': 'Falló la Conexión de Fuente en Tiempo Real',
    'dashboard.websocket.failedConnectionDescription': 'No se pudo establecer la conexión a los precios en vivo después de múltiples intentos. Por favor, verifica tu conexión a internet o inténtalo de nuevo más tarde.',

    'zod.email.invalid': 'Dirección de correo electrónico no válida.',
    'zod.password.required': 'La contraseña es obligatoria.',
    'zod.password.minLength': 'La contraseña debe tener al menos 8 caracteres.',
    'zod.password.lowercase': 'La contraseña debe contener al menos una letra minúscula.',
    'zod.password.uppercase': 'La contraseña debe contener al menos una letra mayúscula.',
    'zod.password.number': 'La contraseña debe contener al menos un número.',
    'zod.password.specialChar': 'La contraseña debe contener al menos un carácter especial.',
    'zod.password.confirmMatch': 'Las contraseñas no coinciden.',
    'zod.apiKey.short': 'La Clave API parece demasiado corta.',
    'zod.apiSecret.short': 'El Secreto API parece demasiado corto.',
    'zod.password.currentRequired': 'La contraseña actual es obligatoria.',
    'zod.password.newMinLength': 'La contraseña nueva debe tener al menos 8 caracteres.',
    'zod.password.newLowercase': 'La contraseña nueva debe contener al menos una letra minúscula.',
    'zod.password.newUppercase': 'La contraseña nueva debe contener al menos una letra mayúscula.',
    'zod.password.newNumber': 'La contraseña nueva debe contener al menos un número.',
    'zod.password.newSpecialChar': 'La contraseña nueva debe contener al menos un carácter especial.',
    'zod.password.newConfirmMatch': 'Las contraseñas nuevas no coinciden.',
    'zod.order.selectCrypto': 'Por favor selecciona una criptomoneda.',
    'zod.order.positiveNumber': 'Debe ser un número positivo.',
  },
  fr: {
    'app.name': 'SimulTradex',
    'app.loadingMessage': 'Chargement de SimulTradex...',
    'settings.myAccount': 'Mon Compte',
    'settings.accountSettings': 'Paramètres du Compte',
    'settings.language': 'Langue',
    'settings.logout': 'Se Déconnecter',
    'dashboard.title': 'Tableau de Bord',
    'dashboard.marketOverview': 'Aperçu du Marché',
    'dashboard.orderSimulator': 'Simulateur d\'Ordres',
    'dashboard.opportunitySimulator': 'Simulateur d\'Opportunités',
    'login.title': 'Se Connecter',
    'login.description': 'Connectez-vous à votre compte',
    'login.emailLabel': 'E-mail',
    'login.emailPlaceholder': 'vous@example.com',
    'login.passwordLabel': 'Mot de passe',
    'login.submitButton': 'Se Connecter',
    'login.signupPrompt': 'Vous n\'avez pas de compte ?',
    'login.signupLink': 'S\'inscrire',
    'login.error.invalidCredentials': 'Email ou mot de passe incorrect.',
    'signup.title': 'S\'inscrire',
    'signup.description': 'Créez votre compte',
    'signup.emailLabel': 'E-mail',
    'signup.emailPlaceholder': 'vous@example.com',
    'signup.passwordLabel': 'Mot de passe',
    'signup.confirmPasswordLabel': 'Confirmer le mot de passe',
    'signup.submitButton': 'S\'inscrire',
    'signup.loginPrompt': 'Vous avez déjà un compte ?',
    'signup.loginLink': 'Se Connecter',
    'signup.error.unknown': 'Une erreur inconnue est survenue.',

    'account.apiKey.title': "Connexion API Binance",
    'account.apiKey.description': "Connectez votre compte Binance pour récupérer les données en temps réel. Vos clés sont stockées localement (simulation).",
    'account.apiKey.connectedStatus': "Connecté à l'API Binance.",
    'account.apiKey.disconnectButton': "Déconnecter",
    'account.apiKey.apiKeyLabel': "Clé API",
    'account.apiKey.apiKeyPlaceholder': "Votre clé API Binance",
    'account.apiKey.apiSecretLabel': "Secret API",
    'account.apiKey.apiSecretPlaceholder': "Votre secret API Binance",
    'account.apiKey.connectButton': "Se connecter à Binance",
    'account.apiKey.error.connectionFailed': "Échec de la connexion : Clé API ou Secret invalide.",
    'account.apiKey.toast.connectionFailedTitle': "Échec de la Connexion API",
    'account.apiKey.toast.connectionFailedDescription': "Clé API ou Secret invalide.",
    'account.apiKey.toast.connectedTitle': "API Connectée",
    'account.apiKey.toast.connectedDescription': "Connexion réussie à l'API Binance.",

    'account.passwordChange.title': "Changer le Mot de Passe",
    'account.passwordChange.description': "Mettez à jour le mot de passe de votre compte.",
    'account.passwordChange.currentPasswordLabel': "Mot de Passe Actuel",
    'account.passwordChange.newPasswordLabel': "Nouveau Mot de Passe",
    'account.passwordChange.confirmNewPasswordLabel': "Confirmer le Nouveau Mot de Passe",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "Changer le Mot de Passe",
    'account.passwordChange.toast.changedTitle': "Mot de Passe Changé",
    'account.passwordChange.toast.changedDescription': "Votre mot de passe a été mis à jour avec succès.",
    'account.passwordChange.toast.failedTitle': "Échec du Changement de Mot de Passe",
    'account.passwordChange.toast.failedDescriptionIncorrect': "Mot de passe actuel incorrect.",

    'account.page.title': "Paramètres du Compte",
    'account.page.userInfoTitle': "Informations Utilisateur",
    'account.page.emailLabel': "E-mail:",

    'dashboard.cryptoCard.tooltip.reason': "Raison:",
    'dashboard.cryptoCard.tooltip.confidence': "Confiance:",
    'dashboard.cryptoCard.trend.upward': "Tendance haussière",
    'dashboard.cryptoCard.trend.downward': "Tendance baissière",
    'dashboard.cryptoCard.trend.sideways': "Tendance latérale",
    'dashboard.cryptoCard.trend.notAvailable': "Tendance N/A",

    'dashboard.opportunityList.title': "Simulateur d'Opportunités",
    'dashboard.opportunityList.description': "Opportunités de trade potentielles basées sur les prix actuels et les pourcentages de profit cibles.",
    'dashboard.opportunityList.table.header.crypto': "Crypto",
    'dashboard.opportunityList.table.header.currentPrice': "Prix Actuel",
    'dashboard.opportunityList.table.header.targetSell': "Vente Cible (+Profit)",
    'dashboard.opportunityList.table.header.potentialGain': "Gain Potentiel",
    'dashboard.opportunityList.emptyMessage': "Aucune opportunité à afficher pour le moment, ou les prix sont encore en cours de chargement.",

    'dashboard.orderSimulator.title': "Simulateur d'Ordres",
    'dashboard.orderSimulator.description': "Simulez un ordre d'achat et de vente pour estimer le profit ou la perte potentiels. Entrez la quantité, le prix d'achat et le prix de vente. Les prix actuels du marché sont pré-remplis pour le prix d'achat.",
    'dashboard.orderSimulator.cryptoLabel': "Cryptomonnaie",
    'dashboard.orderSimulator.selectPlaceholder': "Sélectionnez une crypto",
    'dashboard.orderSimulator.tradingPairDesc': "Paire de Trading : {symbol}/{quoteCurrency}",
    'dashboard.orderSimulator.quantityLabel': "Quantité ({symbol})",
    'dashboard.orderSimulator.quantityLabelNoSymbol': "Quantité",
    'dashboard.orderSimulator.buyPriceLabel': "Prix d'Achat ({quoteCurrency} par unité)",
    'dashboard.orderSimulator.sellPriceLabel': "Prix de Vente ({quoteCurrency} par unité)",
    'dashboard.orderSimulator.commissionDesc': "Une commission de {rate}% sera appliquée aux transactions d'achat et de vente.",
    'dashboard.orderSimulator.submitButton': "Simuler le Trade",
    'dashboard.orderSimulator.toast.errorTitle': "Erreur de Simulation",
    'dashboard.orderSimulator.toast.errorSellPrice': "Le prix de vente doit être supérieur au prix d'achat.",
    'dashboard.orderSimulator.toast.completeTitle': "Simulation Terminée",
    'dashboard.orderSimulator.toast.completeDescription': "Trade simulé pour {quantity} {symbol} traité.",
    'dashboard.orderSimulator.result.title': "Résultat de Simulation pour {quantity} {symbol}",
    'dashboard.orderSimulator.result.grossProfit': "Profit Brut:",
    'dashboard.orderSimulator.result.totalCommission': "Commission Totale:",
    'dashboard.orderSimulator.result.netProfitLoss': "Profit / Perte Net(te):",

    'dashboard.websocket.connectedTitle': 'Flux en Temps Réel Connecté',
    'dashboard.websocket.connectedDescription': 'Les prix en direct de Binance sont maintenant actifs.',
    'dashboard.websocket.errorTitle': 'Erreur du Flux en Temps Réel',
    'dashboard.websocket.errorDescription': 'Un problème est survenu avec le flux de prix en direct. Tentative de reconnexion.',
    'dashboard.websocket.disconnectedTitle': 'Flux en Temps Réel Déconnecté',
    'dashboard.websocket.reconnectingDescription': 'Tentative de reconnexion aux prix en direct... Tentative {attempt}/{maxAttempts}',
    'dashboard.websocket.failedConnectionTitle': 'Échec de Connexion du Flux en Temps Réel',
    'dashboard.websocket.failedConnectionDescription': 'Impossible d\'établir la connexion aux prix en direct après plusieurs tentatives. Veuillez vérifier votre connexion Internet ou réessayer plus tard.',

    'zod.email.invalid': 'Adresse e-mail invalide.',
    'zod.password.required': 'Le mot de passe est requis.',
    'zod.password.minLength': 'Le mot de passe doit comporter au moins 8 caractères.',
    'zod.password.lowercase': 'Le mot de passe doit contenir au moins une lettre minuscule.',
    'zod.password.uppercase': 'Le mot de passe doit contenir au moins une lettre majuscule.',
    'zod.password.number': 'Le mot de passe doit contenir au moins un chiffre.',
    'zod.password.specialChar': 'Le mot de passe doit contenir au moins un caractère spécial.',
    'zod.password.confirmMatch': 'Les mots de passe ne correspondent pas.',
    'zod.apiKey.short': 'La clé API semble trop courte.',
    'zod.apiSecret.short': 'Le secret API semble trop court.',
    'zod.password.currentRequired': 'Le mot de passe actuel est requis.',
    'zod.password.newMinLength': 'Le nouveau mot de passe doit comporter au moins 8 caractères.',
    'zod.password.newLowercase': 'Le nouveau mot de passe doit contenir au moins une lettre minuscule.',
    'zod.password.newUppercase': 'Le nouveau mot de passe doit contenir au moins une lettre majuscule.',
    'zod.password.newNumber': 'Le nouveau mot de passe doit contenir au moins un chiffre.',
    'zod.password.newSpecialChar': 'Le nouveau mot de passe doit contenir au moins un caractère spécial.',
    'zod.password.newConfirmMatch': 'Les nouveaux mots de passe ne correspondent pas.',
    'zod.order.selectCrypto': 'Veuillez sélectionner une cryptomonnaie.',
    'zod.order.positiveNumber': 'Doit être un nombre positif.',
  },
  hi: {
    'app.name': 'सिमुलट्रेडेक्स',
    'app.loadingMessage': 'सिमुलट्रेडेक्स लोड हो रहा है...',
    'settings.myAccount': 'मेरा खाता',
    'settings.accountSettings': 'खाता सेटिंग्स',
    'settings.language': 'भाषा',
    'settings.logout': 'लॉग आउट करें',
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.marketOverview': 'बाज़ार अवलोकन',
    'dashboard.orderSimulator': 'ऑर्डर सिम्युलेटर',
    'dashboard.opportunitySimulator': 'अवसर सिम्युलेटर',
    'login.title': 'लॉग इन करें',
    'login.description': 'अपने खाते में लॉग इन करें',
    'login.emailLabel': 'ईमेल',
    'login.emailPlaceholder': 'aap@udaharan.com',
    'login.passwordLabel': 'पासवर्ड',
    'login.submitButton': 'लॉग इन करें',
    'login.signupPrompt': 'खाता नहीं है?',
    'login.signupLink': 'साइन अप करें',
    'login.error.invalidCredentials': 'अमान्य ईमेल या पासवर्ड।',
    'signup.title': 'साइन अप करें',
    'signup.description': 'अपना खाता बनाएं',
    'signup.emailLabel': 'ईमेल',
    'signup.emailPlaceholder': 'aap@udaharan.com',
    'signup.passwordLabel': 'पासवर्ड',
    'signup.confirmPasswordLabel': 'पासवर्ड की पुष्टि करें',
    'signup.submitButton': 'साइन अप करें',
    'signup.loginPrompt': 'पहले से ही एक खाता है?',
    'signup.loginLink': 'लॉग इन करें',
    'signup.error.unknown': 'एक अज्ञात त्रुटि हुई।',

    'account.apiKey.title': "बायनेंस एपीआई कनेक्शन",
    'account.apiKey.description': "वास्तविक समय डेटा प्राप्त करने के लिए अपने बायनेंस खाते को कनेक्ट करें। आपकी कुंजियाँ स्थानीय रूप से संग्रहीत हैं (मॉक)।",
    'account.apiKey.connectedStatus': "बायनेंस एपीआई से जुड़ा।",
    'account.apiKey.disconnectButton': "डिस्कनेक्ट करें",
    'account.apiKey.apiKeyLabel': "एपीआई कुंजी",
    'account.apiKey.apiKeyPlaceholder': "आपकी बायनेंस एपीआई कुंजी",
    'account.apiKey.apiSecretLabel': "एपीआई रहस्य",
    'account.apiKey.apiSecretPlaceholder': "आपका बायनेंस एपीआई रहस्य",
    'account.apiKey.connectButton': "बायनेंस से कनेक्ट करें",
    'account.apiKey.error.connectionFailed': "कनेक्शन विफल: अमान्य एपीआई कुंजी या रहस्य।",
    'account.apiKey.toast.connectionFailedTitle': "एपीआई कनेक्शन विफल",
    'account.apiKey.toast.connectionFailedDescription': "अमान्य एपीआई कुंजी या रहस्य।",
    'account.apiKey.toast.connectedTitle': "एपीआई जुड़ा",
    'account.apiKey.toast.connectedDescription': "बायनेंस एपीआई से सफलतापूर्वक जुड़ा।",

    'account.passwordChange.title': "पासवर्ड बदलें",
    'account.passwordChange.description': "अपने खाते का पासवर्ड अपडेट करें।",
    'account.passwordChange.currentPasswordLabel': "वर्तमान पासवर्ड",
    'account.passwordChange.newPasswordLabel': "नया पासवर्ड",
    'account.passwordChange.confirmNewPasswordLabel': "नए पासवर्ड की पुष्टि करें",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "पासवर्ड बदलें",
    'account.passwordChange.toast.changedTitle': "पासवर्ड बदला गया",
    'account.passwordChange.toast.changedDescription': "आपका पासवर्ड सफलतापूर्वक अपडेट किया गया है।",
    'account.passwordChange.toast.failedTitle': "पासवर्ड बदलने में विफल",
    'account.passwordChange.toast.failedDescriptionIncorrect': "गलत वर्तमान पासवर्ड।",

    'account.page.title': "खाता सेटिंग्स",
    'account.page.userInfoTitle': "उपयोगकर्ता जानकारी",
    'account.page.emailLabel': "ईमेल:",

    'dashboard.cryptoCard.tooltip.reason': "कारण:",
    'dashboard.cryptoCard.tooltip.confidence': "आत्मविश्वास:",
    'dashboard.cryptoCard.trend.upward': "ऊपर की ओर प्रवृत्ति",
    'dashboard.cryptoCard.trend.downward': "नीचे की ओर प्रवृत्ति",
    'dashboard.cryptoCard.trend.sideways': "बग़ल में प्रवृत्ति",
    'dashboard.cryptoCard.trend.notAvailable': "प्रवृत्ति उपलब्ध नहीं",

    'dashboard.opportunityList.title': "अवसर सिम्युलेटर",
    'dashboard.opportunityList.description': "मौजूदा कीमतों और लक्ष्य लाभ प्रतिशत के आधार पर संभावित व्यापार के अवसर।",
    'dashboard.opportunityList.table.header.crypto': "क्रिप्टो",
    'dashboard.opportunityList.table.header.currentPrice': "वर्तमान मूल्य",
    'dashboard.opportunityList.table.header.targetSell': "लक्ष्य बिक्री (+लाभ)",
    'dashboard.opportunityList.table.header.potentialGain': "संभावित लाभ",
    'dashboard.opportunityList.emptyMessage': "वर्तमान में प्रदर्शित करने के लिए कोई अवसर नहीं है, या कीमतें अभी भी लोड हो रही हैं।",

    'dashboard.orderSimulator.title': "ऑर्डर सिम्युलेटर",
    'dashboard.orderSimulator.description': "संभावित लाभ या हानि का अनुमान लगाने के लिए खरीद और बिक्री ऑर्डर का अनुकरण करें। मात्रा, खरीद मूल्य और बिक्री मूल्य इनपुट करें। वर्तमान बाजार मूल्य खरीद मूल्य के लिए पहले से भरे हुए हैं।",
    'dashboard.orderSimulator.cryptoLabel': "क्रिप्टोकरेंसी",
    'dashboard.orderSimulator.selectPlaceholder': "एक क्रिप्टो चुनें",
    'dashboard.orderSimulator.tradingPairDesc': "ट्रेडिंग जोड़ी: {symbol}/{quoteCurrency}",
    'dashboard.orderSimulator.quantityLabel': "मात्रा ({symbol})",
    'dashboard.orderSimulator.quantityLabelNoSymbol': "मात्रा",
    'dashboard.orderSimulator.buyPriceLabel': "खरीद मूल्य ({quoteCurrency} प्रति यूनिट)",
    'dashboard.orderSimulator.sellPriceLabel': "बिक्री मूल्य ({quoteCurrency} प्रति यूनिट)",
    'dashboard.orderSimulator.commissionDesc': "खरीद और बिक्री दोनों लेनदेन पर {rate}% का कमीशन लागू होगा।",
    'dashboard.orderSimulator.submitButton': "ट्रेड का अनुकरण करें",
    'dashboard.orderSimulator.toast.errorTitle': "अनुकरण त्रुटि",
    'dashboard.orderSimulator.toast.errorSellPrice': "बिक्री मूल्य खरीद मूल्य से अधिक होना चाहिए।",
    'dashboard.orderSimulator.toast.completeTitle': "अनुकरण पूरा हुआ",
    'dashboard.orderSimulator.toast.completeDescription': "{quantity} {symbol} के लिए नकली व्यापार संसाधित।",
    'dashboard.orderSimulator.result.title': "{quantity} {symbol} के लिए अनुकरण परिणाम",
    'dashboard.orderSimulator.result.grossProfit': "सकल लाभ:",
    'dashboard.orderSimulator.result.totalCommission': "कुल कमीशन:",
    'dashboard.orderSimulator.result.netProfitLoss': "शुद्ध लाभ / हानि:",

    'dashboard.websocket.connectedTitle': 'रीयल-टाइम फ़ीड कनेक्टेड',
    'dashboard.websocket.connectedDescription': 'बायनेंस से लाइव कीमतें अब सक्रिय हैं।',
    'dashboard.websocket.errorTitle': 'रीयल-टाइम फ़ीड त्रुटि',
    'dashboard.websocket.errorDescription': 'लाइव मूल्य फ़ीड के साथ एक समस्या थी। पुनः कनेक्ट करने का प्रयास किया जा रहा है।',
    'dashboard.websocket.disconnectedTitle': 'रीयल-टाइम फ़ीड डिस्कनेक्ट हो गया',
    'dashboard.websocket.reconnectingDescription': 'लाइव कीमतों से पुनः कनेक्ट करने का प्रयास किया जा रहा है... प्रयास {attempt}/{maxAttempts}',
    'dashboard.websocket.failedConnectionTitle': 'रीयल-टाइम फ़ीड कनेक्शन विफल',
    'dashboard.websocket.failedConnectionDescription': 'कई प्रयासों के बाद लाइव कीमतों से कनेक्शन स्थापित नहीं किया जा सका। कृपया अपना इंटरनेट कनेक्शन जांचें या बाद में पुनः प्रयास करें।',

    'zod.email.invalid': 'अमान्य ईमेल पता।',
    'zod.password.required': 'पासवर्ड आवश्यक है।',
    'zod.password.minLength': 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।',
    'zod.password.lowercase': 'पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए।',
    'zod.password.uppercase': 'पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए।',
    'zod.password.number': 'पासवर्ड में कम से कम एक संख्या होनी चाहिए।',
    'zod.password.specialChar': 'पासवर्ड में कम से कम एक विशेष वर्ण होना चाहिए।',
    'zod.password.confirmMatch': 'पासवर्ड मेल नहीं खाते।',
    'zod.apiKey.short': 'एपीआई कुंजी बहुत छोटी लगती है।',
    'zod.apiSecret.short': 'एपीआई रहस्य बहुत छोटा लगता है।',
    'zod.password.currentRequired': 'वर्तमान पासवर्ड आवश्यक है।',
    'zod.password.newMinLength': 'नया पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।',
    'zod.password.newLowercase': 'नए पासवर्ड में कम से कम एक छोटा अक्षर होना चाहिए।',
    'zod.password.newUppercase': 'नए पासवर्ड में कम से कम एक बड़ा अक्षर होना चाहिए।',
    'zod.password.newNumber': 'नए पासवर्ड में कम से कम एक संख्या होनी चाहिए।',
    'zod.password.newSpecialChar': 'नए पासवर्ड में कम से कम एक विशेष वर्ण होना चाहिए।',
    'zod.password.newConfirmMatch': 'नए पासवर्ड मेल नहीं खाते।',
    'zod.order.selectCrypto': 'कृपया एक क्रिप्टोकरेंसी चुनें।',
    'zod.order.positiveNumber': 'एक सकारात्मक संख्या होनी चाहिए।',
  },
  zh: {
    'app.name': 'SimulTradex',
    'app.loadingMessage': '正在加载SimulTradex...',
    'settings.myAccount': '我的账户',
    'settings.accountSettings': '账户设置',
    'settings.language': '语言',
    'settings.logout': '登出',
    'dashboard.title': '仪表板',
    'dashboard.marketOverview': '市场概览',
    'dashboard.orderSimulator': '订单模拟器',
    'dashboard.opportunitySimulator': '机会模拟器',
    'login.title': '登录',
    'login.description': '登录您的帐户',
    'login.emailLabel': '电子邮件',
    'login.emailPlaceholder': 'ni@example.com',
    'login.passwordLabel': '密码',
    'login.submitButton': '登录',
    'login.signupPrompt': '还没有账户？',
    'login.signupLink': '注册',
    'login.error.invalidCredentials': '无效的电子邮件或密码。',
    'signup.title': '注册',
    'signup.description': '创建您的账户',
    'signup.emailLabel': '电子邮件',
    'signup.emailPlaceholder': 'ni@example.com',
    'signup.passwordLabel': '密码',
    'signup.confirmPasswordLabel': '确认密码',
    'signup.submitButton': '注册',
    'signup.loginPrompt': '已经有账户了？',
    'signup.loginLink': '登录',
    'signup.error.unknown': '发生未知错误。',

    'account.apiKey.title': "币安API连接",
    'account.apiKey.description': "连接您的币安账户以获取实时数据。您的密钥存储在本地（模拟）。",
    'account.apiKey.connectedStatus': "已连接到币安API。",
    'account.apiKey.disconnectButton': "断开连接",
    'account.apiKey.apiKeyLabel': "API密钥",
    'account.apiKey.apiKeyPlaceholder': "您的币安API密钥",
    'account.apiKey.apiSecretLabel': "API秘密",
    'account.apiKey.apiSecretPlaceholder': "您的币安API秘密",
    'account.apiKey.connectButton': "连接到币安",
    'account.apiKey.error.connectionFailed': "连接失败：API密钥或秘密无效。",
    'account.apiKey.toast.connectionFailedTitle': "API连接失败",
    'account.apiKey.toast.connectionFailedDescription': "API密钥或秘密无效。",
    'account.apiKey.toast.connectedTitle': "API已连接",
    'account.apiKey.toast.connectedDescription': "成功连接到币安API。",

    'account.passwordChange.title': "更改密码",
    'account.passwordChange.description': "更新您的帐户密码。",
    'account.passwordChange.currentPasswordLabel': "当前密码",
    'account.passwordChange.newPasswordLabel': "新密码",
    'account.passwordChange.confirmNewPasswordLabel': "确认新密码",
    'account.passwordChange.passwordPlaceholder': "••••••••",
    'account.passwordChange.submitButton': "更改密码",
    'account.passwordChange.toast.changedTitle': "密码已更改",
    'account.passwordChange.toast.changedDescription': "您的密码已成功更新。",
    'account.passwordChange.toast.failedTitle': "密码更改失败",
    'account.passwordChange.toast.failedDescriptionIncorrect': "当前密码不正确。",

    'account.page.title': "账户设置",
    'account.page.userInfoTitle': "用户信息",
    'account.page.emailLabel': "电子邮件:",

    'dashboard.cryptoCard.tooltip.reason': "原因:",
    'dashboard.cryptoCard.tooltip.confidence': "置信度:",
    'dashboard.cryptoCard.trend.upward': "上涨趋势",
    'dashboard.cryptoCard.trend.downward': "下跌趋势",
    'dashboard.cryptoCard.trend.sideways': "横盘趋势",
    'dashboard.cryptoCard.trend.notAvailable': "趋势不可用",

    'dashboard.opportunityList.title': "机会模拟器",
    'dashboard.opportunityList.description': "根据当前价格和目标利润百分比的潜在交易机会。",
    'dashboard.opportunityList.table.header.crypto': "加密货币",
    'dashboard.opportunityList.table.header.currentPrice': "当前价格",
    'dashboard.opportunityList.table.header.targetSell': "目标卖出价 (+利润)",
    'dashboard.opportunityList.table.header.potentialGain': "潜在收益",
    'dashboard.opportunityList.emptyMessage': "当前没有可显示的机会，或者价格仍在加载中。",

    'dashboard.orderSimulator.title': "订单模拟器",
    'dashboard.orderSimulator.description': "模拟买入和卖出订单以估算潜在利润或损失。输入数量、买入价格和卖出价格。当前市场价格会自动填充买入价格。",
    'dashboard.orderSimulator.cryptoLabel': "加密货币",
    'dashboard.orderSimulator.selectPlaceholder': "选择一种加密货币",
    'dashboard.orderSimulator.tradingPairDesc': "交易对：{symbol}/{quoteCurrency}",
    'dashboard.orderSimulator.quantityLabel': "数量 ({symbol})",
    'dashboard.orderSimulator.quantityLabelNoSymbol': "数量",
    'dashboard.orderSimulator.buyPriceLabel': "买入价格 ({quoteCurrency}/单位)",
    'dashboard.orderSimulator.sellPriceLabel': "卖出价格 ({quoteCurrency}/单位)",
    'dashboard.orderSimulator.commissionDesc': "买入和卖出交易都将收取{rate}%的佣金。",
    'dashboard.orderSimulator.submitButton': "模拟交易",
    'dashboard.orderSimulator.toast.errorTitle': "模拟错误",
    'dashboard.orderSimulator.toast.errorSellPrice': "卖出价格必须高于买入价格。",
    'dashboard.orderSimulator.toast.completeTitle': "模拟完成",
    'dashboard.orderSimulator.toast.completeDescription': "{quantity} {symbol}的模拟交易已处理。",
    'dashboard.orderSimulator.result.title': "{quantity} {symbol}的模拟结果",
    'dashboard.orderSimulator.result.grossProfit': "毛利润：",
    'dashboard.orderSimulator.result.totalCommission': "总佣金：",
    'dashboard.orderSimulator.result.netProfitLoss': "净利润/亏损：",

    'dashboard.websocket.connectedTitle': '实时数据源已连接',
    'dashboard.websocket.connectedDescription': '来自币安的实时价格现已激活。',
    'dashboard.websocket.errorTitle': '实时数据源错误',
    'dashboard.websocket.errorDescription': '实时价格数据源出现问题。正在尝试重新连接。',
    'dashboard.websocket.disconnectedTitle': '实时数据源已断开',
    'dashboard.websocket.reconnectingDescription': '正在尝试重新连接到实时价格... 尝试次数 {attempt}/{maxAttempts}',
    'dashboard.websocket.failedConnectionTitle': '实时数据源连接失败',
    'dashboard.websocket.failedConnectionDescription': '多次尝试后无法建立与实时价格的连接。请检查您的互联网连接或稍后再试。',

    'zod.email.invalid': '无效的电子邮件地址。',
    'zod.password.required': '密码是必需的。',
    'zod.password.minLength': '密码必须至少为8个字符。',
    'zod.password.lowercase': '密码必须包含至少一个小写字母。',
    'zod.password.uppercase': '密码必须包含至少一个大写字母。',
    'zod.password.number': '密码必须包含至少一个数字。',
    'zod.password.specialChar': '密码必须包含至少一个特殊字符。',
    'zod.password.confirmMatch': '密码不匹配。',
    'zod.apiKey.short': 'API密钥似乎太短。',
    'zod.apiSecret.short': 'API秘密似乎太短。',
    'zod.password.currentRequired': '当前密码是必需的。',
    'zod.password.newMinLength': '新密码必须至少为8个字符。',
    'zod.password.newLowercase': '新密码必须包含至少一个小写字母。',
    'zod.password.newUppercase': '新密码必须包含至少一个大写字母。',
    'zod.password.newNumber': '新密码必须包含至少一个数字。',
    'zod.password.newSpecialChar': '新密码必须包含至少一个特殊字符。',
    'zod.password.newConfirmMatch': '新密码不匹配。',
    'zod.order.selectCrypto': '请选择一种加密货币。',
    'zod.order.positiveNumber': '必须是正数。',
  }
};

const DEFAULT_LANGUAGE: LanguageCode = 'en';

export const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setCurrentLanguage] = useState<LanguageCode>(DEFAULT_LANGUAGE);
  const [translations, setTranslations] = useState<Record<string, string>>(
    translationsData[DEFAULT_LANGUAGE]
  );

  useEffect(() => {
    const storedLanguage = typeof window !== 'undefined' ? localStorage.getItem('simultradex_language') as LanguageCode | null : null;
    if (storedLanguage && translationsData[storedLanguage]) {
      setCurrentLanguage(storedLanguage);
      setTranslations(translationsData[storedLanguage]);
    } else {
      setTranslations(translationsData[DEFAULT_LANGUAGE]);
      if (typeof window !== 'undefined') {
         localStorage.setItem('simultradex_language', DEFAULT_LANGUAGE);
      }
    }
  }, []);

  const setLanguage = useCallback((langCode: LanguageCode) => {
    if (translationsData[langCode]) {
      setCurrentLanguage(langCode);
      setTranslations(translationsData[langCode]);
      if (typeof window !== 'undefined') {
        localStorage.setItem('simultradex_language', langCode);
      }
    } else {
      console.warn(`Language code ${langCode} not found in translations. Falling back to default.`);
      setCurrentLanguage(DEFAULT_LANGUAGE);
      setTranslations(translationsData[DEFAULT_LANGUAGE]);
      if (typeof window !== 'undefined') {
        localStorage.setItem('simultradex_language', DEFAULT_LANGUAGE);
      }
    }
  }, []);
  
  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

    